
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const SessionStatus = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
  LOGGED_OUT: 'LOGGED_OUT'
} as const

export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus]


export const AuditActionType = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REVOKE_SESSION: 'REVOKE_SESSION'
} as const

export type AuditActionType = (typeof AuditActionType)[keyof typeof AuditActionType]


export const SessionResult = {
  WIN: 'WIN',
  LOSE: 'LOSE',
  ABANDONED: 'ABANDONED'
} as const

export type SessionResult = (typeof SessionResult)[keyof typeof SessionResult]


export const GameSessionStatus = {
  WAITING: 'WAITING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  ABANDONED: 'ABANDONED'
} as const

export type GameSessionStatus = (typeof GameSessionStatus)[keyof typeof GameSessionStatus]


export const ForumThreadStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
} as const

export type ForumThreadStatus = (typeof ForumThreadStatus)[keyof typeof ForumThreadStatus]


export const ForumPostType = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE'
} as const

export type ForumPostType = (typeof ForumPostType)[keyof typeof ForumPostType]


export const ForumFlair = {
  GENERAL: 'GENERAL',
  BUG_REPORT: 'BUG_REPORT',
  GUIDE: 'GUIDE',
  SUGGESTION: 'SUGGESTION',
  FAN_ART: 'FAN_ART',
  LOOKING_FOR_PARTY: 'LOOKING_FOR_PARTY',
  PATCH_NOTE: 'PATCH_NOTE'
} as const

export type ForumFlair = (typeof ForumFlair)[keyof typeof ForumFlair]
