
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.5.0
 * Query Engine version: 280c870be64f457428992c43c1f6d557fab6e29e
 */
export const prismaVersion: PrismaVersion = {
  client: "7.5.0",
  engine: "280c870be64f457428992c43c1f6d557fab6e29e"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  UserSession: 'UserSession',
  AuditLog: 'AuditLog',
  Level: 'Level',
  GameProfile: 'GameProfile',
  Achievement: 'Achievement',
  UserAchievement: 'UserAchievement',
  GameRun: 'GameRun',
  GameRunPlayer: 'GameRunPlayer',
  GameSession: 'GameSession',
  GameSessionPlayer: 'GameSessionPlayer',
  UserOnlineStatus: 'UserOnlineStatus',
  ForumCategory: 'ForumCategory',
  ForumThread: 'ForumThread',
  ForumComment: 'ForumComment',
  ForumThreadVote: 'ForumThreadVote',
  ForumCommentVote: 'ForumCommentVote',
  WikiPage: 'WikiPage',
  WikiRevision: 'WikiRevision',
  FileAsset: 'FileAsset',
  DownloadLog: 'DownloadLog',
  DownloadStats: 'DownloadStats'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "userSession" | "auditLog" | "level" | "gameProfile" | "achievement" | "userAchievement" | "gameRun" | "gameRunPlayer" | "gameSession" | "gameSessionPlayer" | "userOnlineStatus" | "forumCategory" | "forumThread" | "forumComment" | "forumThreadVote" | "forumCommentVote" | "wikiPage" | "wikiRevision" | "fileAsset" | "downloadLog" | "downloadStats"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    UserSession: {
      payload: Prisma.$UserSessionPayload<ExtArgs>
      fields: Prisma.UserSessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserSessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserSessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>
        }
        findFirst: {
          args: Prisma.UserSessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserSessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>
        }
        findMany: {
          args: Prisma.UserSessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>[]
        }
        create: {
          args: Prisma.UserSessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>
        }
        createMany: {
          args: Prisma.UserSessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserSessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>[]
        }
        delete: {
          args: Prisma.UserSessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>
        }
        update: {
          args: Prisma.UserSessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>
        }
        deleteMany: {
          args: Prisma.UserSessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserSessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserSessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>[]
        }
        upsert: {
          args: Prisma.UserSessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserSessionPayload>
        }
        aggregate: {
          args: Prisma.UserSessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserSession>
        }
        groupBy: {
          args: Prisma.UserSessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserSessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserSessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserSessionCountAggregateOutputType> | number
        }
      }
    }
    AuditLog: {
      payload: Prisma.$AuditLogPayload<ExtArgs>
      fields: Prisma.AuditLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AuditLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AuditLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>
        }
        findFirst: {
          args: Prisma.AuditLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AuditLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>
        }
        findMany: {
          args: Prisma.AuditLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>[]
        }
        create: {
          args: Prisma.AuditLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>
        }
        createMany: {
          args: Prisma.AuditLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AuditLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>[]
        }
        delete: {
          args: Prisma.AuditLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>
        }
        update: {
          args: Prisma.AuditLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>
        }
        deleteMany: {
          args: Prisma.AuditLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AuditLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AuditLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>[]
        }
        upsert: {
          args: Prisma.AuditLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AuditLogPayload>
        }
        aggregate: {
          args: Prisma.AuditLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAuditLog>
        }
        groupBy: {
          args: Prisma.AuditLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AuditLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.AuditLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AuditLogCountAggregateOutputType> | number
        }
      }
    }
    Level: {
      payload: Prisma.$LevelPayload<ExtArgs>
      fields: Prisma.LevelFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LevelFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LevelFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>
        }
        findFirst: {
          args: Prisma.LevelFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LevelFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>
        }
        findMany: {
          args: Prisma.LevelFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>[]
        }
        create: {
          args: Prisma.LevelCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>
        }
        createMany: {
          args: Prisma.LevelCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LevelCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>[]
        }
        delete: {
          args: Prisma.LevelDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>
        }
        update: {
          args: Prisma.LevelUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>
        }
        deleteMany: {
          args: Prisma.LevelDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LevelUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LevelUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>[]
        }
        upsert: {
          args: Prisma.LevelUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LevelPayload>
        }
        aggregate: {
          args: Prisma.LevelAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLevel>
        }
        groupBy: {
          args: Prisma.LevelGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LevelGroupByOutputType>[]
        }
        count: {
          args: Prisma.LevelCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LevelCountAggregateOutputType> | number
        }
      }
    }
    GameProfile: {
      payload: Prisma.$GameProfilePayload<ExtArgs>
      fields: Prisma.GameProfileFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GameProfileFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GameProfileFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>
        }
        findFirst: {
          args: Prisma.GameProfileFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GameProfileFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>
        }
        findMany: {
          args: Prisma.GameProfileFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>[]
        }
        create: {
          args: Prisma.GameProfileCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>
        }
        createMany: {
          args: Prisma.GameProfileCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GameProfileCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>[]
        }
        delete: {
          args: Prisma.GameProfileDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>
        }
        update: {
          args: Prisma.GameProfileUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>
        }
        deleteMany: {
          args: Prisma.GameProfileDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GameProfileUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GameProfileUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>[]
        }
        upsert: {
          args: Prisma.GameProfileUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameProfilePayload>
        }
        aggregate: {
          args: Prisma.GameProfileAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGameProfile>
        }
        groupBy: {
          args: Prisma.GameProfileGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameProfileGroupByOutputType>[]
        }
        count: {
          args: Prisma.GameProfileCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameProfileCountAggregateOutputType> | number
        }
      }
    }
    Achievement: {
      payload: Prisma.$AchievementPayload<ExtArgs>
      fields: Prisma.AchievementFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AchievementFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AchievementFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>
        }
        findFirst: {
          args: Prisma.AchievementFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AchievementFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>
        }
        findMany: {
          args: Prisma.AchievementFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>[]
        }
        create: {
          args: Prisma.AchievementCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>
        }
        createMany: {
          args: Prisma.AchievementCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AchievementCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>[]
        }
        delete: {
          args: Prisma.AchievementDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>
        }
        update: {
          args: Prisma.AchievementUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>
        }
        deleteMany: {
          args: Prisma.AchievementDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AchievementUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AchievementUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>[]
        }
        upsert: {
          args: Prisma.AchievementUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AchievementPayload>
        }
        aggregate: {
          args: Prisma.AchievementAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAchievement>
        }
        groupBy: {
          args: Prisma.AchievementGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AchievementGroupByOutputType>[]
        }
        count: {
          args: Prisma.AchievementCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AchievementCountAggregateOutputType> | number
        }
      }
    }
    UserAchievement: {
      payload: Prisma.$UserAchievementPayload<ExtArgs>
      fields: Prisma.UserAchievementFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserAchievementFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserAchievementFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        findFirst: {
          args: Prisma.UserAchievementFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserAchievementFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        findMany: {
          args: Prisma.UserAchievementFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>[]
        }
        create: {
          args: Prisma.UserAchievementCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        createMany: {
          args: Prisma.UserAchievementCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserAchievementCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>[]
        }
        delete: {
          args: Prisma.UserAchievementDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        update: {
          args: Prisma.UserAchievementUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        deleteMany: {
          args: Prisma.UserAchievementDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserAchievementUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserAchievementUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>[]
        }
        upsert: {
          args: Prisma.UserAchievementUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAchievementPayload>
        }
        aggregate: {
          args: Prisma.UserAchievementAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserAchievement>
        }
        groupBy: {
          args: Prisma.UserAchievementGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserAchievementGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserAchievementCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserAchievementCountAggregateOutputType> | number
        }
      }
    }
    GameRun: {
      payload: Prisma.$GameRunPayload<ExtArgs>
      fields: Prisma.GameRunFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GameRunFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GameRunFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>
        }
        findFirst: {
          args: Prisma.GameRunFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GameRunFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>
        }
        findMany: {
          args: Prisma.GameRunFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>[]
        }
        create: {
          args: Prisma.GameRunCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>
        }
        createMany: {
          args: Prisma.GameRunCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GameRunCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>[]
        }
        delete: {
          args: Prisma.GameRunDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>
        }
        update: {
          args: Prisma.GameRunUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>
        }
        deleteMany: {
          args: Prisma.GameRunDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GameRunUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GameRunUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>[]
        }
        upsert: {
          args: Prisma.GameRunUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPayload>
        }
        aggregate: {
          args: Prisma.GameRunAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGameRun>
        }
        groupBy: {
          args: Prisma.GameRunGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameRunGroupByOutputType>[]
        }
        count: {
          args: Prisma.GameRunCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameRunCountAggregateOutputType> | number
        }
      }
    }
    GameRunPlayer: {
      payload: Prisma.$GameRunPlayerPayload<ExtArgs>
      fields: Prisma.GameRunPlayerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GameRunPlayerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GameRunPlayerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>
        }
        findFirst: {
          args: Prisma.GameRunPlayerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GameRunPlayerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>
        }
        findMany: {
          args: Prisma.GameRunPlayerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>[]
        }
        create: {
          args: Prisma.GameRunPlayerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>
        }
        createMany: {
          args: Prisma.GameRunPlayerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GameRunPlayerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>[]
        }
        delete: {
          args: Prisma.GameRunPlayerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>
        }
        update: {
          args: Prisma.GameRunPlayerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>
        }
        deleteMany: {
          args: Prisma.GameRunPlayerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GameRunPlayerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GameRunPlayerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>[]
        }
        upsert: {
          args: Prisma.GameRunPlayerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameRunPlayerPayload>
        }
        aggregate: {
          args: Prisma.GameRunPlayerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGameRunPlayer>
        }
        groupBy: {
          args: Prisma.GameRunPlayerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameRunPlayerGroupByOutputType>[]
        }
        count: {
          args: Prisma.GameRunPlayerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameRunPlayerCountAggregateOutputType> | number
        }
      }
    }
    GameSession: {
      payload: Prisma.$GameSessionPayload<ExtArgs>
      fields: Prisma.GameSessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GameSessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GameSessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>
        }
        findFirst: {
          args: Prisma.GameSessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GameSessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>
        }
        findMany: {
          args: Prisma.GameSessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>[]
        }
        create: {
          args: Prisma.GameSessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>
        }
        createMany: {
          args: Prisma.GameSessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GameSessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>[]
        }
        delete: {
          args: Prisma.GameSessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>
        }
        update: {
          args: Prisma.GameSessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>
        }
        deleteMany: {
          args: Prisma.GameSessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GameSessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GameSessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>[]
        }
        upsert: {
          args: Prisma.GameSessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPayload>
        }
        aggregate: {
          args: Prisma.GameSessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGameSession>
        }
        groupBy: {
          args: Prisma.GameSessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameSessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.GameSessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameSessionCountAggregateOutputType> | number
        }
      }
    }
    GameSessionPlayer: {
      payload: Prisma.$GameSessionPlayerPayload<ExtArgs>
      fields: Prisma.GameSessionPlayerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GameSessionPlayerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GameSessionPlayerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>
        }
        findFirst: {
          args: Prisma.GameSessionPlayerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GameSessionPlayerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>
        }
        findMany: {
          args: Prisma.GameSessionPlayerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>[]
        }
        create: {
          args: Prisma.GameSessionPlayerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>
        }
        createMany: {
          args: Prisma.GameSessionPlayerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.GameSessionPlayerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>[]
        }
        delete: {
          args: Prisma.GameSessionPlayerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>
        }
        update: {
          args: Prisma.GameSessionPlayerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>
        }
        deleteMany: {
          args: Prisma.GameSessionPlayerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GameSessionPlayerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.GameSessionPlayerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>[]
        }
        upsert: {
          args: Prisma.GameSessionPlayerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GameSessionPlayerPayload>
        }
        aggregate: {
          args: Prisma.GameSessionPlayerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGameSessionPlayer>
        }
        groupBy: {
          args: Prisma.GameSessionPlayerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameSessionPlayerGroupByOutputType>[]
        }
        count: {
          args: Prisma.GameSessionPlayerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GameSessionPlayerCountAggregateOutputType> | number
        }
      }
    }
    UserOnlineStatus: {
      payload: Prisma.$UserOnlineStatusPayload<ExtArgs>
      fields: Prisma.UserOnlineStatusFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserOnlineStatusFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserOnlineStatusFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>
        }
        findFirst: {
          args: Prisma.UserOnlineStatusFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserOnlineStatusFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>
        }
        findMany: {
          args: Prisma.UserOnlineStatusFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>[]
        }
        create: {
          args: Prisma.UserOnlineStatusCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>
        }
        createMany: {
          args: Prisma.UserOnlineStatusCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserOnlineStatusCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>[]
        }
        delete: {
          args: Prisma.UserOnlineStatusDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>
        }
        update: {
          args: Prisma.UserOnlineStatusUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>
        }
        deleteMany: {
          args: Prisma.UserOnlineStatusDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserOnlineStatusUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserOnlineStatusUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>[]
        }
        upsert: {
          args: Prisma.UserOnlineStatusUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserOnlineStatusPayload>
        }
        aggregate: {
          args: Prisma.UserOnlineStatusAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserOnlineStatus>
        }
        groupBy: {
          args: Prisma.UserOnlineStatusGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserOnlineStatusGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserOnlineStatusCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserOnlineStatusCountAggregateOutputType> | number
        }
      }
    }
    ForumCategory: {
      payload: Prisma.$ForumCategoryPayload<ExtArgs>
      fields: Prisma.ForumCategoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ForumCategoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ForumCategoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>
        }
        findFirst: {
          args: Prisma.ForumCategoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ForumCategoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>
        }
        findMany: {
          args: Prisma.ForumCategoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>[]
        }
        create: {
          args: Prisma.ForumCategoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>
        }
        createMany: {
          args: Prisma.ForumCategoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ForumCategoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>[]
        }
        delete: {
          args: Prisma.ForumCategoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>
        }
        update: {
          args: Prisma.ForumCategoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>
        }
        deleteMany: {
          args: Prisma.ForumCategoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ForumCategoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ForumCategoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>[]
        }
        upsert: {
          args: Prisma.ForumCategoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCategoryPayload>
        }
        aggregate: {
          args: Prisma.ForumCategoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateForumCategory>
        }
        groupBy: {
          args: Prisma.ForumCategoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumCategoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.ForumCategoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumCategoryCountAggregateOutputType> | number
        }
      }
    }
    ForumThread: {
      payload: Prisma.$ForumThreadPayload<ExtArgs>
      fields: Prisma.ForumThreadFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ForumThreadFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ForumThreadFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>
        }
        findFirst: {
          args: Prisma.ForumThreadFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ForumThreadFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>
        }
        findMany: {
          args: Prisma.ForumThreadFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>[]
        }
        create: {
          args: Prisma.ForumThreadCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>
        }
        createMany: {
          args: Prisma.ForumThreadCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ForumThreadCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>[]
        }
        delete: {
          args: Prisma.ForumThreadDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>
        }
        update: {
          args: Prisma.ForumThreadUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>
        }
        deleteMany: {
          args: Prisma.ForumThreadDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ForumThreadUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ForumThreadUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>[]
        }
        upsert: {
          args: Prisma.ForumThreadUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadPayload>
        }
        aggregate: {
          args: Prisma.ForumThreadAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateForumThread>
        }
        groupBy: {
          args: Prisma.ForumThreadGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumThreadGroupByOutputType>[]
        }
        count: {
          args: Prisma.ForumThreadCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumThreadCountAggregateOutputType> | number
        }
      }
    }
    ForumComment: {
      payload: Prisma.$ForumCommentPayload<ExtArgs>
      fields: Prisma.ForumCommentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ForumCommentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ForumCommentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>
        }
        findFirst: {
          args: Prisma.ForumCommentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ForumCommentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>
        }
        findMany: {
          args: Prisma.ForumCommentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>[]
        }
        create: {
          args: Prisma.ForumCommentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>
        }
        createMany: {
          args: Prisma.ForumCommentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ForumCommentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>[]
        }
        delete: {
          args: Prisma.ForumCommentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>
        }
        update: {
          args: Prisma.ForumCommentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>
        }
        deleteMany: {
          args: Prisma.ForumCommentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ForumCommentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ForumCommentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>[]
        }
        upsert: {
          args: Prisma.ForumCommentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentPayload>
        }
        aggregate: {
          args: Prisma.ForumCommentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateForumComment>
        }
        groupBy: {
          args: Prisma.ForumCommentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumCommentGroupByOutputType>[]
        }
        count: {
          args: Prisma.ForumCommentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumCommentCountAggregateOutputType> | number
        }
      }
    }
    ForumThreadVote: {
      payload: Prisma.$ForumThreadVotePayload<ExtArgs>
      fields: Prisma.ForumThreadVoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ForumThreadVoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ForumThreadVoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>
        }
        findFirst: {
          args: Prisma.ForumThreadVoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ForumThreadVoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>
        }
        findMany: {
          args: Prisma.ForumThreadVoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>[]
        }
        create: {
          args: Prisma.ForumThreadVoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>
        }
        createMany: {
          args: Prisma.ForumThreadVoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ForumThreadVoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>[]
        }
        delete: {
          args: Prisma.ForumThreadVoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>
        }
        update: {
          args: Prisma.ForumThreadVoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>
        }
        deleteMany: {
          args: Prisma.ForumThreadVoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ForumThreadVoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ForumThreadVoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>[]
        }
        upsert: {
          args: Prisma.ForumThreadVoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumThreadVotePayload>
        }
        aggregate: {
          args: Prisma.ForumThreadVoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateForumThreadVote>
        }
        groupBy: {
          args: Prisma.ForumThreadVoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumThreadVoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.ForumThreadVoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumThreadVoteCountAggregateOutputType> | number
        }
      }
    }
    ForumCommentVote: {
      payload: Prisma.$ForumCommentVotePayload<ExtArgs>
      fields: Prisma.ForumCommentVoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ForumCommentVoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ForumCommentVoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>
        }
        findFirst: {
          args: Prisma.ForumCommentVoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ForumCommentVoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>
        }
        findMany: {
          args: Prisma.ForumCommentVoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>[]
        }
        create: {
          args: Prisma.ForumCommentVoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>
        }
        createMany: {
          args: Prisma.ForumCommentVoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ForumCommentVoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>[]
        }
        delete: {
          args: Prisma.ForumCommentVoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>
        }
        update: {
          args: Prisma.ForumCommentVoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>
        }
        deleteMany: {
          args: Prisma.ForumCommentVoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ForumCommentVoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ForumCommentVoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>[]
        }
        upsert: {
          args: Prisma.ForumCommentVoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ForumCommentVotePayload>
        }
        aggregate: {
          args: Prisma.ForumCommentVoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateForumCommentVote>
        }
        groupBy: {
          args: Prisma.ForumCommentVoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumCommentVoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.ForumCommentVoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ForumCommentVoteCountAggregateOutputType> | number
        }
      }
    }
    WikiPage: {
      payload: Prisma.$WikiPagePayload<ExtArgs>
      fields: Prisma.WikiPageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WikiPageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WikiPageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>
        }
        findFirst: {
          args: Prisma.WikiPageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WikiPageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>
        }
        findMany: {
          args: Prisma.WikiPageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>[]
        }
        create: {
          args: Prisma.WikiPageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>
        }
        createMany: {
          args: Prisma.WikiPageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WikiPageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>[]
        }
        delete: {
          args: Prisma.WikiPageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>
        }
        update: {
          args: Prisma.WikiPageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>
        }
        deleteMany: {
          args: Prisma.WikiPageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WikiPageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WikiPageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>[]
        }
        upsert: {
          args: Prisma.WikiPageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiPagePayload>
        }
        aggregate: {
          args: Prisma.WikiPageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWikiPage>
        }
        groupBy: {
          args: Prisma.WikiPageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WikiPageGroupByOutputType>[]
        }
        count: {
          args: Prisma.WikiPageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WikiPageCountAggregateOutputType> | number
        }
      }
    }
    WikiRevision: {
      payload: Prisma.$WikiRevisionPayload<ExtArgs>
      fields: Prisma.WikiRevisionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WikiRevisionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WikiRevisionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>
        }
        findFirst: {
          args: Prisma.WikiRevisionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WikiRevisionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>
        }
        findMany: {
          args: Prisma.WikiRevisionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>[]
        }
        create: {
          args: Prisma.WikiRevisionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>
        }
        createMany: {
          args: Prisma.WikiRevisionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WikiRevisionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>[]
        }
        delete: {
          args: Prisma.WikiRevisionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>
        }
        update: {
          args: Prisma.WikiRevisionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>
        }
        deleteMany: {
          args: Prisma.WikiRevisionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WikiRevisionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WikiRevisionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>[]
        }
        upsert: {
          args: Prisma.WikiRevisionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiRevisionPayload>
        }
        aggregate: {
          args: Prisma.WikiRevisionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWikiRevision>
        }
        groupBy: {
          args: Prisma.WikiRevisionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WikiRevisionGroupByOutputType>[]
        }
        count: {
          args: Prisma.WikiRevisionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WikiRevisionCountAggregateOutputType> | number
        }
      }
    }
    FileAsset: {
      payload: Prisma.$FileAssetPayload<ExtArgs>
      fields: Prisma.FileAssetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FileAssetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FileAssetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>
        }
        findFirst: {
          args: Prisma.FileAssetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FileAssetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>
        }
        findMany: {
          args: Prisma.FileAssetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>[]
        }
        create: {
          args: Prisma.FileAssetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>
        }
        createMany: {
          args: Prisma.FileAssetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FileAssetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>[]
        }
        delete: {
          args: Prisma.FileAssetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>
        }
        update: {
          args: Prisma.FileAssetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>
        }
        deleteMany: {
          args: Prisma.FileAssetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FileAssetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FileAssetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>[]
        }
        upsert: {
          args: Prisma.FileAssetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileAssetPayload>
        }
        aggregate: {
          args: Prisma.FileAssetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFileAsset>
        }
        groupBy: {
          args: Prisma.FileAssetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileAssetGroupByOutputType>[]
        }
        count: {
          args: Prisma.FileAssetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileAssetCountAggregateOutputType> | number
        }
      }
    }
    DownloadLog: {
      payload: Prisma.$DownloadLogPayload<ExtArgs>
      fields: Prisma.DownloadLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DownloadLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DownloadLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>
        }
        findFirst: {
          args: Prisma.DownloadLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DownloadLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>
        }
        findMany: {
          args: Prisma.DownloadLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>[]
        }
        create: {
          args: Prisma.DownloadLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>
        }
        createMany: {
          args: Prisma.DownloadLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DownloadLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>[]
        }
        delete: {
          args: Prisma.DownloadLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>
        }
        update: {
          args: Prisma.DownloadLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>
        }
        deleteMany: {
          args: Prisma.DownloadLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DownloadLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DownloadLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>[]
        }
        upsert: {
          args: Prisma.DownloadLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadLogPayload>
        }
        aggregate: {
          args: Prisma.DownloadLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDownloadLog>
        }
        groupBy: {
          args: Prisma.DownloadLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DownloadLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.DownloadLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DownloadLogCountAggregateOutputType> | number
        }
      }
    }
    DownloadStats: {
      payload: Prisma.$DownloadStatsPayload<ExtArgs>
      fields: Prisma.DownloadStatsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DownloadStatsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DownloadStatsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>
        }
        findFirst: {
          args: Prisma.DownloadStatsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DownloadStatsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>
        }
        findMany: {
          args: Prisma.DownloadStatsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>[]
        }
        create: {
          args: Prisma.DownloadStatsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>
        }
        createMany: {
          args: Prisma.DownloadStatsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DownloadStatsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>[]
        }
        delete: {
          args: Prisma.DownloadStatsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>
        }
        update: {
          args: Prisma.DownloadStatsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>
        }
        deleteMany: {
          args: Prisma.DownloadStatsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DownloadStatsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DownloadStatsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>[]
        }
        upsert: {
          args: Prisma.DownloadStatsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DownloadStatsPayload>
        }
        aggregate: {
          args: Prisma.DownloadStatsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDownloadStats>
        }
        groupBy: {
          args: Prisma.DownloadStatsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DownloadStatsGroupByOutputType>[]
        }
        count: {
          args: Prisma.DownloadStatsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DownloadStatsCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  displayName: 'displayName',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const UserSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sessionId: 'sessionId',
  platform: 'platform',
  loginTime: 'loginTime',
  logoutTime: 'logoutTime',
  deviceInfo: 'deviceInfo',
  ipAddress: 'ipAddress',
  status: 'status'
} as const

export type UserSessionScalarFieldEnum = (typeof UserSessionScalarFieldEnum)[keyof typeof UserSessionScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  actionType: 'actionType',
  entityName: 'entityName',
  entityId: 'entityId',
  oldValue: 'oldValue',
  newValue: 'newValue',
  timestamp: 'timestamp',
  ipAddress: 'ipAddress'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const LevelScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  order: 'order'
} as const

export type LevelScalarFieldEnum = (typeof LevelScalarFieldEnum)[keyof typeof LevelScalarFieldEnum]


export const GameProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  totalPlayTime: 'totalPlayTime',
  totalSessions: 'totalSessions',
  totalWins: 'totalWins',
  totalLosses: 'totalLosses',
  totalAbandoned: 'totalAbandoned',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GameProfileScalarFieldEnum = (typeof GameProfileScalarFieldEnum)[keyof typeof GameProfileScalarFieldEnum]


export const AchievementScalarFieldEnum = {
  id: 'id',
  name: 'name',
  criteriaCode: 'criteriaCode',
  badgeImageUrl: 'badgeImageUrl',
  rewardPoints: 'rewardPoints'
} as const

export type AchievementScalarFieldEnum = (typeof AchievementScalarFieldEnum)[keyof typeof AchievementScalarFieldEnum]


export const UserAchievementScalarFieldEnum = {
  gameProfileId: 'gameProfileId',
  achievementId: 'achievementId',
  achievedAt: 'achievedAt'
} as const

export type UserAchievementScalarFieldEnum = (typeof UserAchievementScalarFieldEnum)[keyof typeof UserAchievementScalarFieldEnum]


export const GameRunScalarFieldEnum = {
  id: 'id',
  totalLevels: 'totalLevels',
  isCompleted: 'isCompleted',
  totalTimeSec: 'totalTimeSec',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  lobbyId: 'lobbyId'
} as const

export type GameRunScalarFieldEnum = (typeof GameRunScalarFieldEnum)[keyof typeof GameRunScalarFieldEnum]


export const GameRunPlayerScalarFieldEnum = {
  runId: 'runId',
  gameProfileId: 'gameProfileId',
  isHost: 'isHost'
} as const

export type GameRunPlayerScalarFieldEnum = (typeof GameRunPlayerScalarFieldEnum)[keyof typeof GameRunPlayerScalarFieldEnum]


export const GameSessionScalarFieldEnum = {
  id: 'id',
  runId: 'runId',
  levelId: 'levelId',
  status: 'status',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  minPlayers: 'minPlayers',
  maxPlayers: 'maxPlayers',
  result: 'result',
  completionTimeSec: 'completionTimeSec'
} as const

export type GameSessionScalarFieldEnum = (typeof GameSessionScalarFieldEnum)[keyof typeof GameSessionScalarFieldEnum]


export const GameSessionPlayerScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  gameProfileId: 'gameProfileId',
  isAbsent: 'isAbsent',
  leftAt: 'leftAt'
} as const

export type GameSessionPlayerScalarFieldEnum = (typeof GameSessionPlayerScalarFieldEnum)[keyof typeof GameSessionPlayerScalarFieldEnum]


export const UserOnlineStatusScalarFieldEnum = {
  userId: 'userId',
  isOnline: 'isOnline',
  lastOnline: 'lastOnline',
  onlinePlatforms: 'onlinePlatforms',
  updatedAt: 'updatedAt'
} as const

export type UserOnlineStatusScalarFieldEnum = (typeof UserOnlineStatusScalarFieldEnum)[keyof typeof UserOnlineStatusScalarFieldEnum]


export const ForumCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  iconUrl: 'iconUrl',
  isOfficial: 'isOfficial',
  displayOrder: 'displayOrder'
} as const

export type ForumCategoryScalarFieldEnum = (typeof ForumCategoryScalarFieldEnum)[keyof typeof ForumCategoryScalarFieldEnum]


export const ForumThreadScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  categoryId: 'categoryId',
  authorId: 'authorId',
  content: 'content',
  imageUrl: 'imageUrl',
  postType: 'postType',
  flair: 'flair',
  viewCount: 'viewCount',
  score: 'score',
  commentCount: 'commentCount',
  isPinned: 'isPinned',
  isLocked: 'isLocked',
  isAnnouncement: 'isAnnouncement',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumThreadScalarFieldEnum = (typeof ForumThreadScalarFieldEnum)[keyof typeof ForumThreadScalarFieldEnum]


export const ForumCommentScalarFieldEnum = {
  id: 'id',
  threadId: 'threadId',
  authorId: 'authorId',
  content: 'content',
  parentId: 'parentId',
  score: 'score',
  isDeleted: 'isDeleted',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ForumCommentScalarFieldEnum = (typeof ForumCommentScalarFieldEnum)[keyof typeof ForumCommentScalarFieldEnum]


export const ForumThreadVoteScalarFieldEnum = {
  userId: 'userId',
  threadId: 'threadId',
  value: 'value'
} as const

export type ForumThreadVoteScalarFieldEnum = (typeof ForumThreadVoteScalarFieldEnum)[keyof typeof ForumThreadVoteScalarFieldEnum]


export const ForumCommentVoteScalarFieldEnum = {
  userId: 'userId',
  commentId: 'commentId',
  value: 'value'
} as const

export type ForumCommentVoteScalarFieldEnum = (typeof ForumCommentVoteScalarFieldEnum)[keyof typeof ForumCommentVoteScalarFieldEnum]


export const WikiPageScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  metadataJson: 'metadataJson',
  latestRevisionId: 'latestRevisionId'
} as const

export type WikiPageScalarFieldEnum = (typeof WikiPageScalarFieldEnum)[keyof typeof WikiPageScalarFieldEnum]


export const WikiRevisionScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  authorId: 'authorId',
  content: 'content',
  createdAt: 'createdAt'
} as const

export type WikiRevisionScalarFieldEnum = (typeof WikiRevisionScalarFieldEnum)[keyof typeof WikiRevisionScalarFieldEnum]


export const FileAssetScalarFieldEnum = {
  id: 'id',
  fileName: 'fileName',
  fileVersion: 'fileVersion',
  filePath: 'filePath',
  fileSize: 'fileSize',
  mimeType: 'mimeType',
  uploadedAt: 'uploadedAt',
  updatedAt: 'updatedAt'
} as const

export type FileAssetScalarFieldEnum = (typeof FileAssetScalarFieldEnum)[keyof typeof FileAssetScalarFieldEnum]


export const DownloadLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fileVersion: 'fileVersion',
  bytesSent: 'bytesSent',
  clientIp: 'clientIp',
  downloadedAt: 'downloadedAt'
} as const

export type DownloadLogScalarFieldEnum = (typeof DownloadLogScalarFieldEnum)[keyof typeof DownloadLogScalarFieldEnum]


export const DownloadStatsScalarFieldEnum = {
  id: 'id',
  fileAssetId: 'fileAssetId',
  date: 'date',
  downloadCount: 'downloadCount',
  totalBytesSent: 'totalBytesSent'
} as const

export type DownloadStatsScalarFieldEnum = (typeof DownloadStatsScalarFieldEnum)[keyof typeof DownloadStatsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Role[]'
 */
export type ListEnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'SessionStatus'
 */
export type EnumSessionStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SessionStatus'>
    


/**
 * Reference to a field of type 'SessionStatus[]'
 */
export type ListEnumSessionStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SessionStatus[]'>
    


/**
 * Reference to a field of type 'AuditActionType'
 */
export type EnumAuditActionTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AuditActionType'>
    


/**
 * Reference to a field of type 'AuditActionType[]'
 */
export type ListEnumAuditActionTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AuditActionType[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'GameSessionStatus'
 */
export type EnumGameSessionStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'GameSessionStatus'>
    


/**
 * Reference to a field of type 'GameSessionStatus[]'
 */
export type ListEnumGameSessionStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'GameSessionStatus[]'>
    


/**
 * Reference to a field of type 'SessionResult'
 */
export type EnumSessionResultFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SessionResult'>
    


/**
 * Reference to a field of type 'SessionResult[]'
 */
export type ListEnumSessionResultFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SessionResult[]'>
    


/**
 * Reference to a field of type 'ForumPostType'
 */
export type EnumForumPostTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ForumPostType'>
    


/**
 * Reference to a field of type 'ForumPostType[]'
 */
export type ListEnumForumPostTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ForumPostType[]'>
    


/**
 * Reference to a field of type 'ForumFlair'
 */
export type EnumForumFlairFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ForumFlair'>
    


/**
 * Reference to a field of type 'ForumFlair[]'
 */
export type ListEnumForumFlairFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ForumFlair[]'>
    


/**
 * Reference to a field of type 'ForumThreadStatus'
 */
export type EnumForumThreadStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ForumThreadStatus'>
    


/**
 * Reference to a field of type 'ForumThreadStatus[]'
 */
export type ListEnumForumThreadStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ForumThreadStatus[]'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'BigInt[]'
 */
export type ListBigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  userSession?: Prisma.UserSessionOmit
  auditLog?: Prisma.AuditLogOmit
  level?: Prisma.LevelOmit
  gameProfile?: Prisma.GameProfileOmit
  achievement?: Prisma.AchievementOmit
  userAchievement?: Prisma.UserAchievementOmit
  gameRun?: Prisma.GameRunOmit
  gameRunPlayer?: Prisma.GameRunPlayerOmit
  gameSession?: Prisma.GameSessionOmit
  gameSessionPlayer?: Prisma.GameSessionPlayerOmit
  userOnlineStatus?: Prisma.UserOnlineStatusOmit
  forumCategory?: Prisma.ForumCategoryOmit
  forumThread?: Prisma.ForumThreadOmit
  forumComment?: Prisma.ForumCommentOmit
  forumThreadVote?: Prisma.ForumThreadVoteOmit
  forumCommentVote?: Prisma.ForumCommentVoteOmit
  wikiPage?: Prisma.WikiPageOmit
  wikiRevision?: Prisma.WikiRevisionOmit
  fileAsset?: Prisma.FileAssetOmit
  downloadLog?: Prisma.DownloadLogOmit
  downloadStats?: Prisma.DownloadStatsOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

