
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DownloadStats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DownloadStats
 * 
 */
export type DownloadStatsModel = runtime.Types.Result.DefaultSelection<Prisma.$DownloadStatsPayload>

export type AggregateDownloadStats = {
  _count: DownloadStatsCountAggregateOutputType | null
  _avg: DownloadStatsAvgAggregateOutputType | null
  _sum: DownloadStatsSumAggregateOutputType | null
  _min: DownloadStatsMinAggregateOutputType | null
  _max: DownloadStatsMaxAggregateOutputType | null
}

export type DownloadStatsAvgAggregateOutputType = {
  downloadCount: number | null
  totalBytesSent: number | null
}

export type DownloadStatsSumAggregateOutputType = {
  downloadCount: bigint | null
  totalBytesSent: bigint | null
}

export type DownloadStatsMinAggregateOutputType = {
  id: string | null
  fileAssetId: string | null
  date: Date | null
  downloadCount: bigint | null
  totalBytesSent: bigint | null
}

export type DownloadStatsMaxAggregateOutputType = {
  id: string | null
  fileAssetId: string | null
  date: Date | null
  downloadCount: bigint | null
  totalBytesSent: bigint | null
}

export type DownloadStatsCountAggregateOutputType = {
  id: number
  fileAssetId: number
  date: number
  downloadCount: number
  totalBytesSent: number
  _all: number
}


export type DownloadStatsAvgAggregateInputType = {
  downloadCount?: true
  totalBytesSent?: true
}

export type DownloadStatsSumAggregateInputType = {
  downloadCount?: true
  totalBytesSent?: true
}

export type DownloadStatsMinAggregateInputType = {
  id?: true
  fileAssetId?: true
  date?: true
  downloadCount?: true
  totalBytesSent?: true
}

export type DownloadStatsMaxAggregateInputType = {
  id?: true
  fileAssetId?: true
  date?: true
  downloadCount?: true
  totalBytesSent?: true
}

export type DownloadStatsCountAggregateInputType = {
  id?: true
  fileAssetId?: true
  date?: true
  downloadCount?: true
  totalBytesSent?: true
  _all?: true
}

export type DownloadStatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DownloadStats to aggregate.
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DownloadStats to fetch.
   */
  orderBy?: Prisma.DownloadStatsOrderByWithRelationInput | Prisma.DownloadStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DownloadStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DownloadStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DownloadStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DownloadStats
  **/
  _count?: true | DownloadStatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DownloadStatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DownloadStatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DownloadStatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DownloadStatsMaxAggregateInputType
}

export type GetDownloadStatsAggregateType<T extends DownloadStatsAggregateArgs> = {
      [P in keyof T & keyof AggregateDownloadStats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDownloadStats[P]>
    : Prisma.GetScalarType<T[P], AggregateDownloadStats[P]>
}




export type DownloadStatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DownloadStatsWhereInput
  orderBy?: Prisma.DownloadStatsOrderByWithAggregationInput | Prisma.DownloadStatsOrderByWithAggregationInput[]
  by: Prisma.DownloadStatsScalarFieldEnum[] | Prisma.DownloadStatsScalarFieldEnum
  having?: Prisma.DownloadStatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DownloadStatsCountAggregateInputType | true
  _avg?: DownloadStatsAvgAggregateInputType
  _sum?: DownloadStatsSumAggregateInputType
  _min?: DownloadStatsMinAggregateInputType
  _max?: DownloadStatsMaxAggregateInputType
}

export type DownloadStatsGroupByOutputType = {
  id: string
  fileAssetId: string
  date: Date
  downloadCount: bigint
  totalBytesSent: bigint
  _count: DownloadStatsCountAggregateOutputType | null
  _avg: DownloadStatsAvgAggregateOutputType | null
  _sum: DownloadStatsSumAggregateOutputType | null
  _min: DownloadStatsMinAggregateOutputType | null
  _max: DownloadStatsMaxAggregateOutputType | null
}

type GetDownloadStatsGroupByPayload<T extends DownloadStatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DownloadStatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DownloadStatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DownloadStatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DownloadStatsGroupByOutputType[P]>
      }
    >
  >



export type DownloadStatsWhereInput = {
  AND?: Prisma.DownloadStatsWhereInput | Prisma.DownloadStatsWhereInput[]
  OR?: Prisma.DownloadStatsWhereInput[]
  NOT?: Prisma.DownloadStatsWhereInput | Prisma.DownloadStatsWhereInput[]
  id?: Prisma.StringFilter<"DownloadStats"> | string
  fileAssetId?: Prisma.StringFilter<"DownloadStats"> | string
  date?: Prisma.DateTimeFilter<"DownloadStats"> | Date | string
  downloadCount?: Prisma.BigIntFilter<"DownloadStats"> | bigint | number
  totalBytesSent?: Prisma.BigIntFilter<"DownloadStats"> | bigint | number
  fileAsset?: Prisma.XOR<Prisma.FileAssetScalarRelationFilter, Prisma.FileAssetWhereInput>
}

export type DownloadStatsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileAssetId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
  fileAsset?: Prisma.FileAssetOrderByWithRelationInput
}

export type DownloadStatsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fileAssetId_date?: Prisma.DownloadStatsFileAssetIdDateCompoundUniqueInput
  AND?: Prisma.DownloadStatsWhereInput | Prisma.DownloadStatsWhereInput[]
  OR?: Prisma.DownloadStatsWhereInput[]
  NOT?: Prisma.DownloadStatsWhereInput | Prisma.DownloadStatsWhereInput[]
  fileAssetId?: Prisma.StringFilter<"DownloadStats"> | string
  date?: Prisma.DateTimeFilter<"DownloadStats"> | Date | string
  downloadCount?: Prisma.BigIntFilter<"DownloadStats"> | bigint | number
  totalBytesSent?: Prisma.BigIntFilter<"DownloadStats"> | bigint | number
  fileAsset?: Prisma.XOR<Prisma.FileAssetScalarRelationFilter, Prisma.FileAssetWhereInput>
}, "id" | "fileAssetId_date">

export type DownloadStatsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileAssetId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
  _count?: Prisma.DownloadStatsCountOrderByAggregateInput
  _avg?: Prisma.DownloadStatsAvgOrderByAggregateInput
  _max?: Prisma.DownloadStatsMaxOrderByAggregateInput
  _min?: Prisma.DownloadStatsMinOrderByAggregateInput
  _sum?: Prisma.DownloadStatsSumOrderByAggregateInput
}

export type DownloadStatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.DownloadStatsScalarWhereWithAggregatesInput | Prisma.DownloadStatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.DownloadStatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DownloadStatsScalarWhereWithAggregatesInput | Prisma.DownloadStatsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DownloadStats"> | string
  fileAssetId?: Prisma.StringWithAggregatesFilter<"DownloadStats"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"DownloadStats"> | Date | string
  downloadCount?: Prisma.BigIntWithAggregatesFilter<"DownloadStats"> | bigint | number
  totalBytesSent?: Prisma.BigIntWithAggregatesFilter<"DownloadStats"> | bigint | number
}

export type DownloadStatsCreateInput = {
  id?: string
  date: Date | string
  downloadCount?: bigint | number
  totalBytesSent?: bigint | number
  fileAsset: Prisma.FileAssetCreateNestedOneWithoutDownloadStatsInput
}

export type DownloadStatsUncheckedCreateInput = {
  id?: string
  fileAssetId: string
  date: Date | string
  downloadCount?: bigint | number
  totalBytesSent?: bigint | number
}

export type DownloadStatsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fileAsset?: Prisma.FileAssetUpdateOneRequiredWithoutDownloadStatsNestedInput
}

export type DownloadStatsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileAssetId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DownloadStatsCreateManyInput = {
  id?: string
  fileAssetId: string
  date: Date | string
  downloadCount?: bigint | number
  totalBytesSent?: bigint | number
}

export type DownloadStatsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DownloadStatsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileAssetId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DownloadStatsListRelationFilter = {
  every?: Prisma.DownloadStatsWhereInput
  some?: Prisma.DownloadStatsWhereInput
  none?: Prisma.DownloadStatsWhereInput
}

export type DownloadStatsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DownloadStatsFileAssetIdDateCompoundUniqueInput = {
  fileAssetId: string
  date: Date | string
}

export type DownloadStatsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileAssetId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
}

export type DownloadStatsAvgOrderByAggregateInput = {
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
}

export type DownloadStatsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileAssetId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
}

export type DownloadStatsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileAssetId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
}

export type DownloadStatsSumOrderByAggregateInput = {
  downloadCount?: Prisma.SortOrder
  totalBytesSent?: Prisma.SortOrder
}

export type DownloadStatsCreateNestedManyWithoutFileAssetInput = {
  create?: Prisma.XOR<Prisma.DownloadStatsCreateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput> | Prisma.DownloadStatsCreateWithoutFileAssetInput[] | Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput[]
  connectOrCreate?: Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput | Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput[]
  createMany?: Prisma.DownloadStatsCreateManyFileAssetInputEnvelope
  connect?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
}

export type DownloadStatsUncheckedCreateNestedManyWithoutFileAssetInput = {
  create?: Prisma.XOR<Prisma.DownloadStatsCreateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput> | Prisma.DownloadStatsCreateWithoutFileAssetInput[] | Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput[]
  connectOrCreate?: Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput | Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput[]
  createMany?: Prisma.DownloadStatsCreateManyFileAssetInputEnvelope
  connect?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
}

export type DownloadStatsUpdateManyWithoutFileAssetNestedInput = {
  create?: Prisma.XOR<Prisma.DownloadStatsCreateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput> | Prisma.DownloadStatsCreateWithoutFileAssetInput[] | Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput[]
  connectOrCreate?: Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput | Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput[]
  upsert?: Prisma.DownloadStatsUpsertWithWhereUniqueWithoutFileAssetInput | Prisma.DownloadStatsUpsertWithWhereUniqueWithoutFileAssetInput[]
  createMany?: Prisma.DownloadStatsCreateManyFileAssetInputEnvelope
  set?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  disconnect?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  delete?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  connect?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  update?: Prisma.DownloadStatsUpdateWithWhereUniqueWithoutFileAssetInput | Prisma.DownloadStatsUpdateWithWhereUniqueWithoutFileAssetInput[]
  updateMany?: Prisma.DownloadStatsUpdateManyWithWhereWithoutFileAssetInput | Prisma.DownloadStatsUpdateManyWithWhereWithoutFileAssetInput[]
  deleteMany?: Prisma.DownloadStatsScalarWhereInput | Prisma.DownloadStatsScalarWhereInput[]
}

export type DownloadStatsUncheckedUpdateManyWithoutFileAssetNestedInput = {
  create?: Prisma.XOR<Prisma.DownloadStatsCreateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput> | Prisma.DownloadStatsCreateWithoutFileAssetInput[] | Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput[]
  connectOrCreate?: Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput | Prisma.DownloadStatsCreateOrConnectWithoutFileAssetInput[]
  upsert?: Prisma.DownloadStatsUpsertWithWhereUniqueWithoutFileAssetInput | Prisma.DownloadStatsUpsertWithWhereUniqueWithoutFileAssetInput[]
  createMany?: Prisma.DownloadStatsCreateManyFileAssetInputEnvelope
  set?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  disconnect?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  delete?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  connect?: Prisma.DownloadStatsWhereUniqueInput | Prisma.DownloadStatsWhereUniqueInput[]
  update?: Prisma.DownloadStatsUpdateWithWhereUniqueWithoutFileAssetInput | Prisma.DownloadStatsUpdateWithWhereUniqueWithoutFileAssetInput[]
  updateMany?: Prisma.DownloadStatsUpdateManyWithWhereWithoutFileAssetInput | Prisma.DownloadStatsUpdateManyWithWhereWithoutFileAssetInput[]
  deleteMany?: Prisma.DownloadStatsScalarWhereInput | Prisma.DownloadStatsScalarWhereInput[]
}

export type DownloadStatsCreateWithoutFileAssetInput = {
  id?: string
  date: Date | string
  downloadCount?: bigint | number
  totalBytesSent?: bigint | number
}

export type DownloadStatsUncheckedCreateWithoutFileAssetInput = {
  id?: string
  date: Date | string
  downloadCount?: bigint | number
  totalBytesSent?: bigint | number
}

export type DownloadStatsCreateOrConnectWithoutFileAssetInput = {
  where: Prisma.DownloadStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.DownloadStatsCreateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput>
}

export type DownloadStatsCreateManyFileAssetInputEnvelope = {
  data: Prisma.DownloadStatsCreateManyFileAssetInput | Prisma.DownloadStatsCreateManyFileAssetInput[]
  skipDuplicates?: boolean
}

export type DownloadStatsUpsertWithWhereUniqueWithoutFileAssetInput = {
  where: Prisma.DownloadStatsWhereUniqueInput
  update: Prisma.XOR<Prisma.DownloadStatsUpdateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedUpdateWithoutFileAssetInput>
  create: Prisma.XOR<Prisma.DownloadStatsCreateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedCreateWithoutFileAssetInput>
}

export type DownloadStatsUpdateWithWhereUniqueWithoutFileAssetInput = {
  where: Prisma.DownloadStatsWhereUniqueInput
  data: Prisma.XOR<Prisma.DownloadStatsUpdateWithoutFileAssetInput, Prisma.DownloadStatsUncheckedUpdateWithoutFileAssetInput>
}

export type DownloadStatsUpdateManyWithWhereWithoutFileAssetInput = {
  where: Prisma.DownloadStatsScalarWhereInput
  data: Prisma.XOR<Prisma.DownloadStatsUpdateManyMutationInput, Prisma.DownloadStatsUncheckedUpdateManyWithoutFileAssetInput>
}

export type DownloadStatsScalarWhereInput = {
  AND?: Prisma.DownloadStatsScalarWhereInput | Prisma.DownloadStatsScalarWhereInput[]
  OR?: Prisma.DownloadStatsScalarWhereInput[]
  NOT?: Prisma.DownloadStatsScalarWhereInput | Prisma.DownloadStatsScalarWhereInput[]
  id?: Prisma.StringFilter<"DownloadStats"> | string
  fileAssetId?: Prisma.StringFilter<"DownloadStats"> | string
  date?: Prisma.DateTimeFilter<"DownloadStats"> | Date | string
  downloadCount?: Prisma.BigIntFilter<"DownloadStats"> | bigint | number
  totalBytesSent?: Prisma.BigIntFilter<"DownloadStats"> | bigint | number
}

export type DownloadStatsCreateManyFileAssetInput = {
  id?: string
  date: Date | string
  downloadCount?: bigint | number
  totalBytesSent?: bigint | number
}

export type DownloadStatsUpdateWithoutFileAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DownloadStatsUncheckedUpdateWithoutFileAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type DownloadStatsUncheckedUpdateManyWithoutFileAssetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  downloadCount?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  totalBytesSent?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type DownloadStatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileAssetId?: boolean
  date?: boolean
  downloadCount?: boolean
  totalBytesSent?: boolean
  fileAsset?: boolean | Prisma.FileAssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["downloadStats"]>

export type DownloadStatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileAssetId?: boolean
  date?: boolean
  downloadCount?: boolean
  totalBytesSent?: boolean
  fileAsset?: boolean | Prisma.FileAssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["downloadStats"]>

export type DownloadStatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileAssetId?: boolean
  date?: boolean
  downloadCount?: boolean
  totalBytesSent?: boolean
  fileAsset?: boolean | Prisma.FileAssetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["downloadStats"]>

export type DownloadStatsSelectScalar = {
  id?: boolean
  fileAssetId?: boolean
  date?: boolean
  downloadCount?: boolean
  totalBytesSent?: boolean
}

export type DownloadStatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileAssetId" | "date" | "downloadCount" | "totalBytesSent", ExtArgs["result"]["downloadStats"]>
export type DownloadStatsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fileAsset?: boolean | Prisma.FileAssetDefaultArgs<ExtArgs>
}
export type DownloadStatsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fileAsset?: boolean | Prisma.FileAssetDefaultArgs<ExtArgs>
}
export type DownloadStatsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fileAsset?: boolean | Prisma.FileAssetDefaultArgs<ExtArgs>
}

export type $DownloadStatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DownloadStats"
  objects: {
    fileAsset: Prisma.$FileAssetPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileAssetId: string
    date: Date
    downloadCount: bigint
    totalBytesSent: bigint
  }, ExtArgs["result"]["downloadStats"]>
  composites: {}
}

export type DownloadStatsGetPayload<S extends boolean | null | undefined | DownloadStatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload, S>

export type DownloadStatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DownloadStatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DownloadStatsCountAggregateInputType | true
  }

export interface DownloadStatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DownloadStats'], meta: { name: 'DownloadStats' } }
  /**
   * Find zero or one DownloadStats that matches the filter.
   * @param {DownloadStatsFindUniqueArgs} args - Arguments to find a DownloadStats
   * @example
   * // Get one DownloadStats
   * const downloadStats = await prisma.downloadStats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DownloadStatsFindUniqueArgs>(args: Prisma.SelectSubset<T, DownloadStatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DownloadStats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DownloadStatsFindUniqueOrThrowArgs} args - Arguments to find a DownloadStats
   * @example
   * // Get one DownloadStats
   * const downloadStats = await prisma.downloadStats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DownloadStatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DownloadStatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DownloadStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsFindFirstArgs} args - Arguments to find a DownloadStats
   * @example
   * // Get one DownloadStats
   * const downloadStats = await prisma.downloadStats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DownloadStatsFindFirstArgs>(args?: Prisma.SelectSubset<T, DownloadStatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DownloadStats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsFindFirstOrThrowArgs} args - Arguments to find a DownloadStats
   * @example
   * // Get one DownloadStats
   * const downloadStats = await prisma.downloadStats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DownloadStatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DownloadStatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DownloadStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DownloadStats
   * const downloadStats = await prisma.downloadStats.findMany()
   * 
   * // Get first 10 DownloadStats
   * const downloadStats = await prisma.downloadStats.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const downloadStatsWithIdOnly = await prisma.downloadStats.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DownloadStatsFindManyArgs>(args?: Prisma.SelectSubset<T, DownloadStatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DownloadStats.
   * @param {DownloadStatsCreateArgs} args - Arguments to create a DownloadStats.
   * @example
   * // Create one DownloadStats
   * const DownloadStats = await prisma.downloadStats.create({
   *   data: {
   *     // ... data to create a DownloadStats
   *   }
   * })
   * 
   */
  create<T extends DownloadStatsCreateArgs>(args: Prisma.SelectSubset<T, DownloadStatsCreateArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DownloadStats.
   * @param {DownloadStatsCreateManyArgs} args - Arguments to create many DownloadStats.
   * @example
   * // Create many DownloadStats
   * const downloadStats = await prisma.downloadStats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DownloadStatsCreateManyArgs>(args?: Prisma.SelectSubset<T, DownloadStatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DownloadStats and returns the data saved in the database.
   * @param {DownloadStatsCreateManyAndReturnArgs} args - Arguments to create many DownloadStats.
   * @example
   * // Create many DownloadStats
   * const downloadStats = await prisma.downloadStats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DownloadStats and only return the `id`
   * const downloadStatsWithIdOnly = await prisma.downloadStats.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DownloadStatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DownloadStatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DownloadStats.
   * @param {DownloadStatsDeleteArgs} args - Arguments to delete one DownloadStats.
   * @example
   * // Delete one DownloadStats
   * const DownloadStats = await prisma.downloadStats.delete({
   *   where: {
   *     // ... filter to delete one DownloadStats
   *   }
   * })
   * 
   */
  delete<T extends DownloadStatsDeleteArgs>(args: Prisma.SelectSubset<T, DownloadStatsDeleteArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DownloadStats.
   * @param {DownloadStatsUpdateArgs} args - Arguments to update one DownloadStats.
   * @example
   * // Update one DownloadStats
   * const downloadStats = await prisma.downloadStats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DownloadStatsUpdateArgs>(args: Prisma.SelectSubset<T, DownloadStatsUpdateArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DownloadStats.
   * @param {DownloadStatsDeleteManyArgs} args - Arguments to filter DownloadStats to delete.
   * @example
   * // Delete a few DownloadStats
   * const { count } = await prisma.downloadStats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DownloadStatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, DownloadStatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DownloadStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DownloadStats
   * const downloadStats = await prisma.downloadStats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DownloadStatsUpdateManyArgs>(args: Prisma.SelectSubset<T, DownloadStatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DownloadStats and returns the data updated in the database.
   * @param {DownloadStatsUpdateManyAndReturnArgs} args - Arguments to update many DownloadStats.
   * @example
   * // Update many DownloadStats
   * const downloadStats = await prisma.downloadStats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DownloadStats and only return the `id`
   * const downloadStatsWithIdOnly = await prisma.downloadStats.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DownloadStatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DownloadStatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DownloadStats.
   * @param {DownloadStatsUpsertArgs} args - Arguments to update or create a DownloadStats.
   * @example
   * // Update or create a DownloadStats
   * const downloadStats = await prisma.downloadStats.upsert({
   *   create: {
   *     // ... data to create a DownloadStats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DownloadStats we want to update
   *   }
   * })
   */
  upsert<T extends DownloadStatsUpsertArgs>(args: Prisma.SelectSubset<T, DownloadStatsUpsertArgs<ExtArgs>>): Prisma.Prisma__DownloadStatsClient<runtime.Types.Result.GetResult<Prisma.$DownloadStatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DownloadStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsCountArgs} args - Arguments to filter DownloadStats to count.
   * @example
   * // Count the number of DownloadStats
   * const count = await prisma.downloadStats.count({
   *   where: {
   *     // ... the filter for the DownloadStats we want to count
   *   }
   * })
  **/
  count<T extends DownloadStatsCountArgs>(
    args?: Prisma.Subset<T, DownloadStatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DownloadStatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DownloadStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DownloadStatsAggregateArgs>(args: Prisma.Subset<T, DownloadStatsAggregateArgs>): Prisma.PrismaPromise<GetDownloadStatsAggregateType<T>>

  /**
   * Group by DownloadStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DownloadStatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DownloadStatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DownloadStatsGroupByArgs['orderBy'] }
      : { orderBy?: DownloadStatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DownloadStatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDownloadStatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DownloadStats model
 */
readonly fields: DownloadStatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DownloadStats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DownloadStatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fileAsset<T extends Prisma.FileAssetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FileAssetDefaultArgs<ExtArgs>>): Prisma.Prisma__FileAssetClient<runtime.Types.Result.GetResult<Prisma.$FileAssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DownloadStats model
 */
export interface DownloadStatsFieldRefs {
  readonly id: Prisma.FieldRef<"DownloadStats", 'String'>
  readonly fileAssetId: Prisma.FieldRef<"DownloadStats", 'String'>
  readonly date: Prisma.FieldRef<"DownloadStats", 'DateTime'>
  readonly downloadCount: Prisma.FieldRef<"DownloadStats", 'BigInt'>
  readonly totalBytesSent: Prisma.FieldRef<"DownloadStats", 'BigInt'>
}
    

// Custom InputTypes
/**
 * DownloadStats findUnique
 */
export type DownloadStatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * Filter, which DownloadStats to fetch.
   */
  where: Prisma.DownloadStatsWhereUniqueInput
}

/**
 * DownloadStats findUniqueOrThrow
 */
export type DownloadStatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * Filter, which DownloadStats to fetch.
   */
  where: Prisma.DownloadStatsWhereUniqueInput
}

/**
 * DownloadStats findFirst
 */
export type DownloadStatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * Filter, which DownloadStats to fetch.
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DownloadStats to fetch.
   */
  orderBy?: Prisma.DownloadStatsOrderByWithRelationInput | Prisma.DownloadStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DownloadStats.
   */
  cursor?: Prisma.DownloadStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DownloadStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DownloadStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DownloadStats.
   */
  distinct?: Prisma.DownloadStatsScalarFieldEnum | Prisma.DownloadStatsScalarFieldEnum[]
}

/**
 * DownloadStats findFirstOrThrow
 */
export type DownloadStatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * Filter, which DownloadStats to fetch.
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DownloadStats to fetch.
   */
  orderBy?: Prisma.DownloadStatsOrderByWithRelationInput | Prisma.DownloadStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DownloadStats.
   */
  cursor?: Prisma.DownloadStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DownloadStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DownloadStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DownloadStats.
   */
  distinct?: Prisma.DownloadStatsScalarFieldEnum | Prisma.DownloadStatsScalarFieldEnum[]
}

/**
 * DownloadStats findMany
 */
export type DownloadStatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * Filter, which DownloadStats to fetch.
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DownloadStats to fetch.
   */
  orderBy?: Prisma.DownloadStatsOrderByWithRelationInput | Prisma.DownloadStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DownloadStats.
   */
  cursor?: Prisma.DownloadStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DownloadStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DownloadStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DownloadStats.
   */
  distinct?: Prisma.DownloadStatsScalarFieldEnum | Prisma.DownloadStatsScalarFieldEnum[]
}

/**
 * DownloadStats create
 */
export type DownloadStatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * The data needed to create a DownloadStats.
   */
  data: Prisma.XOR<Prisma.DownloadStatsCreateInput, Prisma.DownloadStatsUncheckedCreateInput>
}

/**
 * DownloadStats createMany
 */
export type DownloadStatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DownloadStats.
   */
  data: Prisma.DownloadStatsCreateManyInput | Prisma.DownloadStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DownloadStats createManyAndReturn
 */
export type DownloadStatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * The data used to create many DownloadStats.
   */
  data: Prisma.DownloadStatsCreateManyInput | Prisma.DownloadStatsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DownloadStats update
 */
export type DownloadStatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * The data needed to update a DownloadStats.
   */
  data: Prisma.XOR<Prisma.DownloadStatsUpdateInput, Prisma.DownloadStatsUncheckedUpdateInput>
  /**
   * Choose, which DownloadStats to update.
   */
  where: Prisma.DownloadStatsWhereUniqueInput
}

/**
 * DownloadStats updateMany
 */
export type DownloadStatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DownloadStats.
   */
  data: Prisma.XOR<Prisma.DownloadStatsUpdateManyMutationInput, Prisma.DownloadStatsUncheckedUpdateManyInput>
  /**
   * Filter which DownloadStats to update
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * Limit how many DownloadStats to update.
   */
  limit?: number
}

/**
 * DownloadStats updateManyAndReturn
 */
export type DownloadStatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * The data used to update DownloadStats.
   */
  data: Prisma.XOR<Prisma.DownloadStatsUpdateManyMutationInput, Prisma.DownloadStatsUncheckedUpdateManyInput>
  /**
   * Filter which DownloadStats to update
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * Limit how many DownloadStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DownloadStats upsert
 */
export type DownloadStatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * The filter to search for the DownloadStats to update in case it exists.
   */
  where: Prisma.DownloadStatsWhereUniqueInput
  /**
   * In case the DownloadStats found by the `where` argument doesn't exist, create a new DownloadStats with this data.
   */
  create: Prisma.XOR<Prisma.DownloadStatsCreateInput, Prisma.DownloadStatsUncheckedCreateInput>
  /**
   * In case the DownloadStats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DownloadStatsUpdateInput, Prisma.DownloadStatsUncheckedUpdateInput>
}

/**
 * DownloadStats delete
 */
export type DownloadStatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
  /**
   * Filter which DownloadStats to delete.
   */
  where: Prisma.DownloadStatsWhereUniqueInput
}

/**
 * DownloadStats deleteMany
 */
export type DownloadStatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DownloadStats to delete
   */
  where?: Prisma.DownloadStatsWhereInput
  /**
   * Limit how many DownloadStats to delete.
   */
  limit?: number
}

/**
 * DownloadStats without action
 */
export type DownloadStatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DownloadStats
   */
  select?: Prisma.DownloadStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DownloadStats
   */
  omit?: Prisma.DownloadStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DownloadStatsInclude<ExtArgs> | null
}
