
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ForumThreadVote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ForumThreadVote
 * 
 */
export type ForumThreadVoteModel = runtime.Types.Result.DefaultSelection<Prisma.$ForumThreadVotePayload>

export type AggregateForumThreadVote = {
  _count: ForumThreadVoteCountAggregateOutputType | null
  _avg: ForumThreadVoteAvgAggregateOutputType | null
  _sum: ForumThreadVoteSumAggregateOutputType | null
  _min: ForumThreadVoteMinAggregateOutputType | null
  _max: ForumThreadVoteMaxAggregateOutputType | null
}

export type ForumThreadVoteAvgAggregateOutputType = {
  value: number | null
}

export type ForumThreadVoteSumAggregateOutputType = {
  value: number | null
}

export type ForumThreadVoteMinAggregateOutputType = {
  userId: string | null
  threadId: string | null
  value: number | null
}

export type ForumThreadVoteMaxAggregateOutputType = {
  userId: string | null
  threadId: string | null
  value: number | null
}

export type ForumThreadVoteCountAggregateOutputType = {
  userId: number
  threadId: number
  value: number
  _all: number
}


export type ForumThreadVoteAvgAggregateInputType = {
  value?: true
}

export type ForumThreadVoteSumAggregateInputType = {
  value?: true
}

export type ForumThreadVoteMinAggregateInputType = {
  userId?: true
  threadId?: true
  value?: true
}

export type ForumThreadVoteMaxAggregateInputType = {
  userId?: true
  threadId?: true
  value?: true
}

export type ForumThreadVoteCountAggregateInputType = {
  userId?: true
  threadId?: true
  value?: true
  _all?: true
}

export type ForumThreadVoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumThreadVote to aggregate.
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumThreadVotes to fetch.
   */
  orderBy?: Prisma.ForumThreadVoteOrderByWithRelationInput | Prisma.ForumThreadVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ForumThreadVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumThreadVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumThreadVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ForumThreadVotes
  **/
  _count?: true | ForumThreadVoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ForumThreadVoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ForumThreadVoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ForumThreadVoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ForumThreadVoteMaxAggregateInputType
}

export type GetForumThreadVoteAggregateType<T extends ForumThreadVoteAggregateArgs> = {
      [P in keyof T & keyof AggregateForumThreadVote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateForumThreadVote[P]>
    : Prisma.GetScalarType<T[P], AggregateForumThreadVote[P]>
}




export type ForumThreadVoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ForumThreadVoteWhereInput
  orderBy?: Prisma.ForumThreadVoteOrderByWithAggregationInput | Prisma.ForumThreadVoteOrderByWithAggregationInput[]
  by: Prisma.ForumThreadVoteScalarFieldEnum[] | Prisma.ForumThreadVoteScalarFieldEnum
  having?: Prisma.ForumThreadVoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ForumThreadVoteCountAggregateInputType | true
  _avg?: ForumThreadVoteAvgAggregateInputType
  _sum?: ForumThreadVoteSumAggregateInputType
  _min?: ForumThreadVoteMinAggregateInputType
  _max?: ForumThreadVoteMaxAggregateInputType
}

export type ForumThreadVoteGroupByOutputType = {
  userId: string
  threadId: string
  value: number
  _count: ForumThreadVoteCountAggregateOutputType | null
  _avg: ForumThreadVoteAvgAggregateOutputType | null
  _sum: ForumThreadVoteSumAggregateOutputType | null
  _min: ForumThreadVoteMinAggregateOutputType | null
  _max: ForumThreadVoteMaxAggregateOutputType | null
}

type GetForumThreadVoteGroupByPayload<T extends ForumThreadVoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ForumThreadVoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ForumThreadVoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ForumThreadVoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ForumThreadVoteGroupByOutputType[P]>
      }
    >
  >



export type ForumThreadVoteWhereInput = {
  AND?: Prisma.ForumThreadVoteWhereInput | Prisma.ForumThreadVoteWhereInput[]
  OR?: Prisma.ForumThreadVoteWhereInput[]
  NOT?: Prisma.ForumThreadVoteWhereInput | Prisma.ForumThreadVoteWhereInput[]
  userId?: Prisma.StringFilter<"ForumThreadVote"> | string
  threadId?: Prisma.StringFilter<"ForumThreadVote"> | string
  value?: Prisma.IntFilter<"ForumThreadVote"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  thread?: Prisma.XOR<Prisma.ForumThreadScalarRelationFilter, Prisma.ForumThreadWhereInput>
}

export type ForumThreadVoteOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  thread?: Prisma.ForumThreadOrderByWithRelationInput
}

export type ForumThreadVoteWhereUniqueInput = Prisma.AtLeast<{
  userId_threadId?: Prisma.ForumThreadVoteUserIdThreadIdCompoundUniqueInput
  AND?: Prisma.ForumThreadVoteWhereInput | Prisma.ForumThreadVoteWhereInput[]
  OR?: Prisma.ForumThreadVoteWhereInput[]
  NOT?: Prisma.ForumThreadVoteWhereInput | Prisma.ForumThreadVoteWhereInput[]
  userId?: Prisma.StringFilter<"ForumThreadVote"> | string
  threadId?: Prisma.StringFilter<"ForumThreadVote"> | string
  value?: Prisma.IntFilter<"ForumThreadVote"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  thread?: Prisma.XOR<Prisma.ForumThreadScalarRelationFilter, Prisma.ForumThreadWhereInput>
}, "userId_threadId">

export type ForumThreadVoteOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  _count?: Prisma.ForumThreadVoteCountOrderByAggregateInput
  _avg?: Prisma.ForumThreadVoteAvgOrderByAggregateInput
  _max?: Prisma.ForumThreadVoteMaxOrderByAggregateInput
  _min?: Prisma.ForumThreadVoteMinOrderByAggregateInput
  _sum?: Prisma.ForumThreadVoteSumOrderByAggregateInput
}

export type ForumThreadVoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.ForumThreadVoteScalarWhereWithAggregatesInput | Prisma.ForumThreadVoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.ForumThreadVoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ForumThreadVoteScalarWhereWithAggregatesInput | Prisma.ForumThreadVoteScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"ForumThreadVote"> | string
  threadId?: Prisma.StringWithAggregatesFilter<"ForumThreadVote"> | string
  value?: Prisma.IntWithAggregatesFilter<"ForumThreadVote"> | number
}

export type ForumThreadVoteCreateInput = {
  value: number
  user: Prisma.UserCreateNestedOneWithoutThreadVotesInput
  thread: Prisma.ForumThreadCreateNestedOneWithoutVotesInput
}

export type ForumThreadVoteUncheckedCreateInput = {
  userId: string
  threadId: string
  value: number
}

export type ForumThreadVoteUpdateInput = {
  value?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutThreadVotesNestedInput
  thread?: Prisma.ForumThreadUpdateOneRequiredWithoutVotesNestedInput
}

export type ForumThreadVoteUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumThreadVoteCreateManyInput = {
  userId: string
  threadId: string
  value: number
}

export type ForumThreadVoteUpdateManyMutationInput = {
  value?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumThreadVoteUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumThreadVoteListRelationFilter = {
  every?: Prisma.ForumThreadVoteWhereInput
  some?: Prisma.ForumThreadVoteWhereInput
  none?: Prisma.ForumThreadVoteWhereInput
}

export type ForumThreadVoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ForumThreadVoteUserIdThreadIdCompoundUniqueInput = {
  userId: string
  threadId: string
}

export type ForumThreadVoteCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type ForumThreadVoteAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type ForumThreadVoteMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type ForumThreadVoteMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type ForumThreadVoteSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type ForumThreadVoteCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutUserInput, Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput> | Prisma.ForumThreadVoteCreateWithoutUserInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput | Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyUserInputEnvelope
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
}

export type ForumThreadVoteUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutUserInput, Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput> | Prisma.ForumThreadVoteCreateWithoutUserInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput | Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyUserInputEnvelope
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
}

export type ForumThreadVoteUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutUserInput, Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput> | Prisma.ForumThreadVoteCreateWithoutUserInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput | Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutUserInput | Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyUserInputEnvelope
  set?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  disconnect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  delete?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  update?: Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutUserInput | Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ForumThreadVoteUpdateManyWithWhereWithoutUserInput | Prisma.ForumThreadVoteUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ForumThreadVoteScalarWhereInput | Prisma.ForumThreadVoteScalarWhereInput[]
}

export type ForumThreadVoteUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutUserInput, Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput> | Prisma.ForumThreadVoteCreateWithoutUserInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput | Prisma.ForumThreadVoteCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutUserInput | Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyUserInputEnvelope
  set?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  disconnect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  delete?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  update?: Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutUserInput | Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ForumThreadVoteUpdateManyWithWhereWithoutUserInput | Prisma.ForumThreadVoteUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ForumThreadVoteScalarWhereInput | Prisma.ForumThreadVoteScalarWhereInput[]
}

export type ForumThreadVoteCreateNestedManyWithoutThreadInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput> | Prisma.ForumThreadVoteCreateWithoutThreadInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput | Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyThreadInputEnvelope
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
}

export type ForumThreadVoteUncheckedCreateNestedManyWithoutThreadInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput> | Prisma.ForumThreadVoteCreateWithoutThreadInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput | Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyThreadInputEnvelope
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
}

export type ForumThreadVoteUpdateManyWithoutThreadNestedInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput> | Prisma.ForumThreadVoteCreateWithoutThreadInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput | Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput[]
  upsert?: Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutThreadInput | Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutThreadInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyThreadInputEnvelope
  set?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  disconnect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  delete?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  update?: Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutThreadInput | Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutThreadInput[]
  updateMany?: Prisma.ForumThreadVoteUpdateManyWithWhereWithoutThreadInput | Prisma.ForumThreadVoteUpdateManyWithWhereWithoutThreadInput[]
  deleteMany?: Prisma.ForumThreadVoteScalarWhereInput | Prisma.ForumThreadVoteScalarWhereInput[]
}

export type ForumThreadVoteUncheckedUpdateManyWithoutThreadNestedInput = {
  create?: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput> | Prisma.ForumThreadVoteCreateWithoutThreadInput[] | Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput | Prisma.ForumThreadVoteCreateOrConnectWithoutThreadInput[]
  upsert?: Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutThreadInput | Prisma.ForumThreadVoteUpsertWithWhereUniqueWithoutThreadInput[]
  createMany?: Prisma.ForumThreadVoteCreateManyThreadInputEnvelope
  set?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  disconnect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  delete?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  connect?: Prisma.ForumThreadVoteWhereUniqueInput | Prisma.ForumThreadVoteWhereUniqueInput[]
  update?: Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutThreadInput | Prisma.ForumThreadVoteUpdateWithWhereUniqueWithoutThreadInput[]
  updateMany?: Prisma.ForumThreadVoteUpdateManyWithWhereWithoutThreadInput | Prisma.ForumThreadVoteUpdateManyWithWhereWithoutThreadInput[]
  deleteMany?: Prisma.ForumThreadVoteScalarWhereInput | Prisma.ForumThreadVoteScalarWhereInput[]
}

export type ForumThreadVoteCreateWithoutUserInput = {
  value: number
  thread: Prisma.ForumThreadCreateNestedOneWithoutVotesInput
}

export type ForumThreadVoteUncheckedCreateWithoutUserInput = {
  threadId: string
  value: number
}

export type ForumThreadVoteCreateOrConnectWithoutUserInput = {
  where: Prisma.ForumThreadVoteWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutUserInput, Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput>
}

export type ForumThreadVoteCreateManyUserInputEnvelope = {
  data: Prisma.ForumThreadVoteCreateManyUserInput | Prisma.ForumThreadVoteCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ForumThreadVoteUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ForumThreadVoteWhereUniqueInput
  update: Prisma.XOR<Prisma.ForumThreadVoteUpdateWithoutUserInput, Prisma.ForumThreadVoteUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutUserInput, Prisma.ForumThreadVoteUncheckedCreateWithoutUserInput>
}

export type ForumThreadVoteUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ForumThreadVoteWhereUniqueInput
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateWithoutUserInput, Prisma.ForumThreadVoteUncheckedUpdateWithoutUserInput>
}

export type ForumThreadVoteUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ForumThreadVoteScalarWhereInput
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateManyMutationInput, Prisma.ForumThreadVoteUncheckedUpdateManyWithoutUserInput>
}

export type ForumThreadVoteScalarWhereInput = {
  AND?: Prisma.ForumThreadVoteScalarWhereInput | Prisma.ForumThreadVoteScalarWhereInput[]
  OR?: Prisma.ForumThreadVoteScalarWhereInput[]
  NOT?: Prisma.ForumThreadVoteScalarWhereInput | Prisma.ForumThreadVoteScalarWhereInput[]
  userId?: Prisma.StringFilter<"ForumThreadVote"> | string
  threadId?: Prisma.StringFilter<"ForumThreadVote"> | string
  value?: Prisma.IntFilter<"ForumThreadVote"> | number
}

export type ForumThreadVoteCreateWithoutThreadInput = {
  value: number
  user: Prisma.UserCreateNestedOneWithoutThreadVotesInput
}

export type ForumThreadVoteUncheckedCreateWithoutThreadInput = {
  userId: string
  value: number
}

export type ForumThreadVoteCreateOrConnectWithoutThreadInput = {
  where: Prisma.ForumThreadVoteWhereUniqueInput
  create: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput>
}

export type ForumThreadVoteCreateManyThreadInputEnvelope = {
  data: Prisma.ForumThreadVoteCreateManyThreadInput | Prisma.ForumThreadVoteCreateManyThreadInput[]
  skipDuplicates?: boolean
}

export type ForumThreadVoteUpsertWithWhereUniqueWithoutThreadInput = {
  where: Prisma.ForumThreadVoteWhereUniqueInput
  update: Prisma.XOR<Prisma.ForumThreadVoteUpdateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedUpdateWithoutThreadInput>
  create: Prisma.XOR<Prisma.ForumThreadVoteCreateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedCreateWithoutThreadInput>
}

export type ForumThreadVoteUpdateWithWhereUniqueWithoutThreadInput = {
  where: Prisma.ForumThreadVoteWhereUniqueInput
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateWithoutThreadInput, Prisma.ForumThreadVoteUncheckedUpdateWithoutThreadInput>
}

export type ForumThreadVoteUpdateManyWithWhereWithoutThreadInput = {
  where: Prisma.ForumThreadVoteScalarWhereInput
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateManyMutationInput, Prisma.ForumThreadVoteUncheckedUpdateManyWithoutThreadInput>
}

export type ForumThreadVoteCreateManyUserInput = {
  threadId: string
  value: number
}

export type ForumThreadVoteUpdateWithoutUserInput = {
  value?: Prisma.IntFieldUpdateOperationsInput | number
  thread?: Prisma.ForumThreadUpdateOneRequiredWithoutVotesNestedInput
}

export type ForumThreadVoteUncheckedUpdateWithoutUserInput = {
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumThreadVoteUncheckedUpdateManyWithoutUserInput = {
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumThreadVoteCreateManyThreadInput = {
  userId: string
  value: number
}

export type ForumThreadVoteUpdateWithoutThreadInput = {
  value?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutThreadVotesNestedInput
}

export type ForumThreadVoteUncheckedUpdateWithoutThreadInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ForumThreadVoteUncheckedUpdateManyWithoutThreadInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.IntFieldUpdateOperationsInput | number
}



export type ForumThreadVoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  threadId?: boolean
  value?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  thread?: boolean | Prisma.ForumThreadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumThreadVote"]>

export type ForumThreadVoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  threadId?: boolean
  value?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  thread?: boolean | Prisma.ForumThreadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumThreadVote"]>

export type ForumThreadVoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  threadId?: boolean
  value?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  thread?: boolean | Prisma.ForumThreadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["forumThreadVote"]>

export type ForumThreadVoteSelectScalar = {
  userId?: boolean
  threadId?: boolean
  value?: boolean
}

export type ForumThreadVoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "threadId" | "value", ExtArgs["result"]["forumThreadVote"]>
export type ForumThreadVoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  thread?: boolean | Prisma.ForumThreadDefaultArgs<ExtArgs>
}
export type ForumThreadVoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  thread?: boolean | Prisma.ForumThreadDefaultArgs<ExtArgs>
}
export type ForumThreadVoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  thread?: boolean | Prisma.ForumThreadDefaultArgs<ExtArgs>
}

export type $ForumThreadVotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ForumThreadVote"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    thread: Prisma.$ForumThreadPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    threadId: string
    value: number
  }, ExtArgs["result"]["forumThreadVote"]>
  composites: {}
}

export type ForumThreadVoteGetPayload<S extends boolean | null | undefined | ForumThreadVoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload, S>

export type ForumThreadVoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ForumThreadVoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ForumThreadVoteCountAggregateInputType | true
  }

export interface ForumThreadVoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ForumThreadVote'], meta: { name: 'ForumThreadVote' } }
  /**
   * Find zero or one ForumThreadVote that matches the filter.
   * @param {ForumThreadVoteFindUniqueArgs} args - Arguments to find a ForumThreadVote
   * @example
   * // Get one ForumThreadVote
   * const forumThreadVote = await prisma.forumThreadVote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ForumThreadVoteFindUniqueArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ForumThreadVote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ForumThreadVoteFindUniqueOrThrowArgs} args - Arguments to find a ForumThreadVote
   * @example
   * // Get one ForumThreadVote
   * const forumThreadVote = await prisma.forumThreadVote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ForumThreadVoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumThreadVote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteFindFirstArgs} args - Arguments to find a ForumThreadVote
   * @example
   * // Get one ForumThreadVote
   * const forumThreadVote = await prisma.forumThreadVote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ForumThreadVoteFindFirstArgs>(args?: Prisma.SelectSubset<T, ForumThreadVoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ForumThreadVote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteFindFirstOrThrowArgs} args - Arguments to find a ForumThreadVote
   * @example
   * // Get one ForumThreadVote
   * const forumThreadVote = await prisma.forumThreadVote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ForumThreadVoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ForumThreadVoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ForumThreadVotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ForumThreadVotes
   * const forumThreadVotes = await prisma.forumThreadVote.findMany()
   * 
   * // Get first 10 ForumThreadVotes
   * const forumThreadVotes = await prisma.forumThreadVote.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const forumThreadVoteWithUserIdOnly = await prisma.forumThreadVote.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends ForumThreadVoteFindManyArgs>(args?: Prisma.SelectSubset<T, ForumThreadVoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ForumThreadVote.
   * @param {ForumThreadVoteCreateArgs} args - Arguments to create a ForumThreadVote.
   * @example
   * // Create one ForumThreadVote
   * const ForumThreadVote = await prisma.forumThreadVote.create({
   *   data: {
   *     // ... data to create a ForumThreadVote
   *   }
   * })
   * 
   */
  create<T extends ForumThreadVoteCreateArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteCreateArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ForumThreadVotes.
   * @param {ForumThreadVoteCreateManyArgs} args - Arguments to create many ForumThreadVotes.
   * @example
   * // Create many ForumThreadVotes
   * const forumThreadVote = await prisma.forumThreadVote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ForumThreadVoteCreateManyArgs>(args?: Prisma.SelectSubset<T, ForumThreadVoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ForumThreadVotes and returns the data saved in the database.
   * @param {ForumThreadVoteCreateManyAndReturnArgs} args - Arguments to create many ForumThreadVotes.
   * @example
   * // Create many ForumThreadVotes
   * const forumThreadVote = await prisma.forumThreadVote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ForumThreadVotes and only return the `userId`
   * const forumThreadVoteWithUserIdOnly = await prisma.forumThreadVote.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ForumThreadVoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ForumThreadVoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ForumThreadVote.
   * @param {ForumThreadVoteDeleteArgs} args - Arguments to delete one ForumThreadVote.
   * @example
   * // Delete one ForumThreadVote
   * const ForumThreadVote = await prisma.forumThreadVote.delete({
   *   where: {
   *     // ... filter to delete one ForumThreadVote
   *   }
   * })
   * 
   */
  delete<T extends ForumThreadVoteDeleteArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteDeleteArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ForumThreadVote.
   * @param {ForumThreadVoteUpdateArgs} args - Arguments to update one ForumThreadVote.
   * @example
   * // Update one ForumThreadVote
   * const forumThreadVote = await prisma.forumThreadVote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ForumThreadVoteUpdateArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteUpdateArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ForumThreadVotes.
   * @param {ForumThreadVoteDeleteManyArgs} args - Arguments to filter ForumThreadVotes to delete.
   * @example
   * // Delete a few ForumThreadVotes
   * const { count } = await prisma.forumThreadVote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ForumThreadVoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, ForumThreadVoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumThreadVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ForumThreadVotes
   * const forumThreadVote = await prisma.forumThreadVote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ForumThreadVoteUpdateManyArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ForumThreadVotes and returns the data updated in the database.
   * @param {ForumThreadVoteUpdateManyAndReturnArgs} args - Arguments to update many ForumThreadVotes.
   * @example
   * // Update many ForumThreadVotes
   * const forumThreadVote = await prisma.forumThreadVote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ForumThreadVotes and only return the `userId`
   * const forumThreadVoteWithUserIdOnly = await prisma.forumThreadVote.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ForumThreadVoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ForumThreadVote.
   * @param {ForumThreadVoteUpsertArgs} args - Arguments to update or create a ForumThreadVote.
   * @example
   * // Update or create a ForumThreadVote
   * const forumThreadVote = await prisma.forumThreadVote.upsert({
   *   create: {
   *     // ... data to create a ForumThreadVote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ForumThreadVote we want to update
   *   }
   * })
   */
  upsert<T extends ForumThreadVoteUpsertArgs>(args: Prisma.SelectSubset<T, ForumThreadVoteUpsertArgs<ExtArgs>>): Prisma.Prisma__ForumThreadVoteClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadVotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ForumThreadVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteCountArgs} args - Arguments to filter ForumThreadVotes to count.
   * @example
   * // Count the number of ForumThreadVotes
   * const count = await prisma.forumThreadVote.count({
   *   where: {
   *     // ... the filter for the ForumThreadVotes we want to count
   *   }
   * })
  **/
  count<T extends ForumThreadVoteCountArgs>(
    args?: Prisma.Subset<T, ForumThreadVoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ForumThreadVoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ForumThreadVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ForumThreadVoteAggregateArgs>(args: Prisma.Subset<T, ForumThreadVoteAggregateArgs>): Prisma.PrismaPromise<GetForumThreadVoteAggregateType<T>>

  /**
   * Group by ForumThreadVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ForumThreadVoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ForumThreadVoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ForumThreadVoteGroupByArgs['orderBy'] }
      : { orderBy?: ForumThreadVoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ForumThreadVoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetForumThreadVoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ForumThreadVote model
 */
readonly fields: ForumThreadVoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ForumThreadVote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ForumThreadVoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  thread<T extends Prisma.ForumThreadDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ForumThreadDefaultArgs<ExtArgs>>): Prisma.Prisma__ForumThreadClient<runtime.Types.Result.GetResult<Prisma.$ForumThreadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ForumThreadVote model
 */
export interface ForumThreadVoteFieldRefs {
  readonly userId: Prisma.FieldRef<"ForumThreadVote", 'String'>
  readonly threadId: Prisma.FieldRef<"ForumThreadVote", 'String'>
  readonly value: Prisma.FieldRef<"ForumThreadVote", 'Int'>
}
    

// Custom InputTypes
/**
 * ForumThreadVote findUnique
 */
export type ForumThreadVoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * Filter, which ForumThreadVote to fetch.
   */
  where: Prisma.ForumThreadVoteWhereUniqueInput
}

/**
 * ForumThreadVote findUniqueOrThrow
 */
export type ForumThreadVoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * Filter, which ForumThreadVote to fetch.
   */
  where: Prisma.ForumThreadVoteWhereUniqueInput
}

/**
 * ForumThreadVote findFirst
 */
export type ForumThreadVoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * Filter, which ForumThreadVote to fetch.
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumThreadVotes to fetch.
   */
  orderBy?: Prisma.ForumThreadVoteOrderByWithRelationInput | Prisma.ForumThreadVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumThreadVotes.
   */
  cursor?: Prisma.ForumThreadVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumThreadVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumThreadVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumThreadVotes.
   */
  distinct?: Prisma.ForumThreadVoteScalarFieldEnum | Prisma.ForumThreadVoteScalarFieldEnum[]
}

/**
 * ForumThreadVote findFirstOrThrow
 */
export type ForumThreadVoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * Filter, which ForumThreadVote to fetch.
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumThreadVotes to fetch.
   */
  orderBy?: Prisma.ForumThreadVoteOrderByWithRelationInput | Prisma.ForumThreadVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ForumThreadVotes.
   */
  cursor?: Prisma.ForumThreadVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumThreadVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumThreadVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumThreadVotes.
   */
  distinct?: Prisma.ForumThreadVoteScalarFieldEnum | Prisma.ForumThreadVoteScalarFieldEnum[]
}

/**
 * ForumThreadVote findMany
 */
export type ForumThreadVoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * Filter, which ForumThreadVotes to fetch.
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ForumThreadVotes to fetch.
   */
  orderBy?: Prisma.ForumThreadVoteOrderByWithRelationInput | Prisma.ForumThreadVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ForumThreadVotes.
   */
  cursor?: Prisma.ForumThreadVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ForumThreadVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ForumThreadVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ForumThreadVotes.
   */
  distinct?: Prisma.ForumThreadVoteScalarFieldEnum | Prisma.ForumThreadVoteScalarFieldEnum[]
}

/**
 * ForumThreadVote create
 */
export type ForumThreadVoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * The data needed to create a ForumThreadVote.
   */
  data: Prisma.XOR<Prisma.ForumThreadVoteCreateInput, Prisma.ForumThreadVoteUncheckedCreateInput>
}

/**
 * ForumThreadVote createMany
 */
export type ForumThreadVoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ForumThreadVotes.
   */
  data: Prisma.ForumThreadVoteCreateManyInput | Prisma.ForumThreadVoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ForumThreadVote createManyAndReturn
 */
export type ForumThreadVoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * The data used to create many ForumThreadVotes.
   */
  data: Prisma.ForumThreadVoteCreateManyInput | Prisma.ForumThreadVoteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ForumThreadVote update
 */
export type ForumThreadVoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * The data needed to update a ForumThreadVote.
   */
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateInput, Prisma.ForumThreadVoteUncheckedUpdateInput>
  /**
   * Choose, which ForumThreadVote to update.
   */
  where: Prisma.ForumThreadVoteWhereUniqueInput
}

/**
 * ForumThreadVote updateMany
 */
export type ForumThreadVoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ForumThreadVotes.
   */
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateManyMutationInput, Prisma.ForumThreadVoteUncheckedUpdateManyInput>
  /**
   * Filter which ForumThreadVotes to update
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * Limit how many ForumThreadVotes to update.
   */
  limit?: number
}

/**
 * ForumThreadVote updateManyAndReturn
 */
export type ForumThreadVoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * The data used to update ForumThreadVotes.
   */
  data: Prisma.XOR<Prisma.ForumThreadVoteUpdateManyMutationInput, Prisma.ForumThreadVoteUncheckedUpdateManyInput>
  /**
   * Filter which ForumThreadVotes to update
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * Limit how many ForumThreadVotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ForumThreadVote upsert
 */
export type ForumThreadVoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * The filter to search for the ForumThreadVote to update in case it exists.
   */
  where: Prisma.ForumThreadVoteWhereUniqueInput
  /**
   * In case the ForumThreadVote found by the `where` argument doesn't exist, create a new ForumThreadVote with this data.
   */
  create: Prisma.XOR<Prisma.ForumThreadVoteCreateInput, Prisma.ForumThreadVoteUncheckedCreateInput>
  /**
   * In case the ForumThreadVote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ForumThreadVoteUpdateInput, Prisma.ForumThreadVoteUncheckedUpdateInput>
}

/**
 * ForumThreadVote delete
 */
export type ForumThreadVoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
  /**
   * Filter which ForumThreadVote to delete.
   */
  where: Prisma.ForumThreadVoteWhereUniqueInput
}

/**
 * ForumThreadVote deleteMany
 */
export type ForumThreadVoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ForumThreadVotes to delete
   */
  where?: Prisma.ForumThreadVoteWhereInput
  /**
   * Limit how many ForumThreadVotes to delete.
   */
  limit?: number
}

/**
 * ForumThreadVote without action
 */
export type ForumThreadVoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ForumThreadVote
   */
  select?: Prisma.ForumThreadVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ForumThreadVote
   */
  omit?: Prisma.ForumThreadVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ForumThreadVoteInclude<ExtArgs> | null
}
