
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GameSessionPlayer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GameSessionPlayer
 * 
 */
export type GameSessionPlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$GameSessionPlayerPayload>

export type AggregateGameSessionPlayer = {
  _count: GameSessionPlayerCountAggregateOutputType | null
  _min: GameSessionPlayerMinAggregateOutputType | null
  _max: GameSessionPlayerMaxAggregateOutputType | null
}

export type GameSessionPlayerMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  gameProfileId: string | null
  isAbsent: boolean | null
  leftAt: Date | null
}

export type GameSessionPlayerMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  gameProfileId: string | null
  isAbsent: boolean | null
  leftAt: Date | null
}

export type GameSessionPlayerCountAggregateOutputType = {
  id: number
  sessionId: number
  gameProfileId: number
  isAbsent: number
  leftAt: number
  _all: number
}


export type GameSessionPlayerMinAggregateInputType = {
  id?: true
  sessionId?: true
  gameProfileId?: true
  isAbsent?: true
  leftAt?: true
}

export type GameSessionPlayerMaxAggregateInputType = {
  id?: true
  sessionId?: true
  gameProfileId?: true
  isAbsent?: true
  leftAt?: true
}

export type GameSessionPlayerCountAggregateInputType = {
  id?: true
  sessionId?: true
  gameProfileId?: true
  isAbsent?: true
  leftAt?: true
  _all?: true
}

export type GameSessionPlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GameSessionPlayer to aggregate.
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GameSessionPlayers to fetch.
   */
  orderBy?: Prisma.GameSessionPlayerOrderByWithRelationInput | Prisma.GameSessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GameSessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GameSessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GameSessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GameSessionPlayers
  **/
  _count?: true | GameSessionPlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GameSessionPlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GameSessionPlayerMaxAggregateInputType
}

export type GetGameSessionPlayerAggregateType<T extends GameSessionPlayerAggregateArgs> = {
      [P in keyof T & keyof AggregateGameSessionPlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGameSessionPlayer[P]>
    : Prisma.GetScalarType<T[P], AggregateGameSessionPlayer[P]>
}




export type GameSessionPlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GameSessionPlayerWhereInput
  orderBy?: Prisma.GameSessionPlayerOrderByWithAggregationInput | Prisma.GameSessionPlayerOrderByWithAggregationInput[]
  by: Prisma.GameSessionPlayerScalarFieldEnum[] | Prisma.GameSessionPlayerScalarFieldEnum
  having?: Prisma.GameSessionPlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GameSessionPlayerCountAggregateInputType | true
  _min?: GameSessionPlayerMinAggregateInputType
  _max?: GameSessionPlayerMaxAggregateInputType
}

export type GameSessionPlayerGroupByOutputType = {
  id: string
  sessionId: string
  gameProfileId: string
  isAbsent: boolean
  leftAt: Date | null
  _count: GameSessionPlayerCountAggregateOutputType | null
  _min: GameSessionPlayerMinAggregateOutputType | null
  _max: GameSessionPlayerMaxAggregateOutputType | null
}

type GetGameSessionPlayerGroupByPayload<T extends GameSessionPlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GameSessionPlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GameSessionPlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GameSessionPlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GameSessionPlayerGroupByOutputType[P]>
      }
    >
  >



export type GameSessionPlayerWhereInput = {
  AND?: Prisma.GameSessionPlayerWhereInput | Prisma.GameSessionPlayerWhereInput[]
  OR?: Prisma.GameSessionPlayerWhereInput[]
  NOT?: Prisma.GameSessionPlayerWhereInput | Prisma.GameSessionPlayerWhereInput[]
  id?: Prisma.StringFilter<"GameSessionPlayer"> | string
  sessionId?: Prisma.StringFilter<"GameSessionPlayer"> | string
  gameProfileId?: Prisma.StringFilter<"GameSessionPlayer"> | string
  isAbsent?: Prisma.BoolFilter<"GameSessionPlayer"> | boolean
  leftAt?: Prisma.DateTimeNullableFilter<"GameSessionPlayer"> | Date | string | null
  session?: Prisma.XOR<Prisma.GameSessionScalarRelationFilter, Prisma.GameSessionWhereInput>
  gameProfile?: Prisma.XOR<Prisma.GameProfileScalarRelationFilter, Prisma.GameProfileWhereInput>
}

export type GameSessionPlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  gameProfileId?: Prisma.SortOrder
  isAbsent?: Prisma.SortOrder
  leftAt?: Prisma.SortOrderInput | Prisma.SortOrder
  session?: Prisma.GameSessionOrderByWithRelationInput
  gameProfile?: Prisma.GameProfileOrderByWithRelationInput
}

export type GameSessionPlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  sessionId_gameProfileId?: Prisma.GameSessionPlayerSessionIdGameProfileIdCompoundUniqueInput
  AND?: Prisma.GameSessionPlayerWhereInput | Prisma.GameSessionPlayerWhereInput[]
  OR?: Prisma.GameSessionPlayerWhereInput[]
  NOT?: Prisma.GameSessionPlayerWhereInput | Prisma.GameSessionPlayerWhereInput[]
  sessionId?: Prisma.StringFilter<"GameSessionPlayer"> | string
  gameProfileId?: Prisma.StringFilter<"GameSessionPlayer"> | string
  isAbsent?: Prisma.BoolFilter<"GameSessionPlayer"> | boolean
  leftAt?: Prisma.DateTimeNullableFilter<"GameSessionPlayer"> | Date | string | null
  session?: Prisma.XOR<Prisma.GameSessionScalarRelationFilter, Prisma.GameSessionWhereInput>
  gameProfile?: Prisma.XOR<Prisma.GameProfileScalarRelationFilter, Prisma.GameProfileWhereInput>
}, "id" | "sessionId_gameProfileId">

export type GameSessionPlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  gameProfileId?: Prisma.SortOrder
  isAbsent?: Prisma.SortOrder
  leftAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.GameSessionPlayerCountOrderByAggregateInput
  _max?: Prisma.GameSessionPlayerMaxOrderByAggregateInput
  _min?: Prisma.GameSessionPlayerMinOrderByAggregateInput
}

export type GameSessionPlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.GameSessionPlayerScalarWhereWithAggregatesInput | Prisma.GameSessionPlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.GameSessionPlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GameSessionPlayerScalarWhereWithAggregatesInput | Prisma.GameSessionPlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GameSessionPlayer"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"GameSessionPlayer"> | string
  gameProfileId?: Prisma.StringWithAggregatesFilter<"GameSessionPlayer"> | string
  isAbsent?: Prisma.BoolWithAggregatesFilter<"GameSessionPlayer"> | boolean
  leftAt?: Prisma.DateTimeNullableWithAggregatesFilter<"GameSessionPlayer"> | Date | string | null
}

export type GameSessionPlayerCreateInput = {
  id?: string
  isAbsent?: boolean
  leftAt?: Date | string | null
  session: Prisma.GameSessionCreateNestedOneWithoutPlayersInput
  gameProfile: Prisma.GameProfileCreateNestedOneWithoutGameSessionPlayersInput
}

export type GameSessionPlayerUncheckedCreateInput = {
  id?: string
  sessionId: string
  gameProfileId: string
  isAbsent?: boolean
  leftAt?: Date | string | null
}

export type GameSessionPlayerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  session?: Prisma.GameSessionUpdateOneRequiredWithoutPlayersNestedInput
  gameProfile?: Prisma.GameProfileUpdateOneRequiredWithoutGameSessionPlayersNestedInput
}

export type GameSessionPlayerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  gameProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameSessionPlayerCreateManyInput = {
  id?: string
  sessionId: string
  gameProfileId: string
  isAbsent?: boolean
  leftAt?: Date | string | null
}

export type GameSessionPlayerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameSessionPlayerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  gameProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameSessionPlayerListRelationFilter = {
  every?: Prisma.GameSessionPlayerWhereInput
  some?: Prisma.GameSessionPlayerWhereInput
  none?: Prisma.GameSessionPlayerWhereInput
}

export type GameSessionPlayerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GameSessionPlayerSessionIdGameProfileIdCompoundUniqueInput = {
  sessionId: string
  gameProfileId: string
}

export type GameSessionPlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  gameProfileId?: Prisma.SortOrder
  isAbsent?: Prisma.SortOrder
  leftAt?: Prisma.SortOrder
}

export type GameSessionPlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  gameProfileId?: Prisma.SortOrder
  isAbsent?: Prisma.SortOrder
  leftAt?: Prisma.SortOrder
}

export type GameSessionPlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  gameProfileId?: Prisma.SortOrder
  isAbsent?: Prisma.SortOrder
  leftAt?: Prisma.SortOrder
}

export type GameSessionPlayerCreateNestedManyWithoutGameProfileInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput> | Prisma.GameSessionPlayerCreateWithoutGameProfileInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput | Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput[]
  createMany?: Prisma.GameSessionPlayerCreateManyGameProfileInputEnvelope
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
}

export type GameSessionPlayerUncheckedCreateNestedManyWithoutGameProfileInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput> | Prisma.GameSessionPlayerCreateWithoutGameProfileInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput | Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput[]
  createMany?: Prisma.GameSessionPlayerCreateManyGameProfileInputEnvelope
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
}

export type GameSessionPlayerUpdateManyWithoutGameProfileNestedInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput> | Prisma.GameSessionPlayerCreateWithoutGameProfileInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput | Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput[]
  upsert?: Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutGameProfileInput | Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutGameProfileInput[]
  createMany?: Prisma.GameSessionPlayerCreateManyGameProfileInputEnvelope
  set?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  delete?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  update?: Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutGameProfileInput | Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutGameProfileInput[]
  updateMany?: Prisma.GameSessionPlayerUpdateManyWithWhereWithoutGameProfileInput | Prisma.GameSessionPlayerUpdateManyWithWhereWithoutGameProfileInput[]
  deleteMany?: Prisma.GameSessionPlayerScalarWhereInput | Prisma.GameSessionPlayerScalarWhereInput[]
}

export type GameSessionPlayerUncheckedUpdateManyWithoutGameProfileNestedInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput> | Prisma.GameSessionPlayerCreateWithoutGameProfileInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput | Prisma.GameSessionPlayerCreateOrConnectWithoutGameProfileInput[]
  upsert?: Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutGameProfileInput | Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutGameProfileInput[]
  createMany?: Prisma.GameSessionPlayerCreateManyGameProfileInputEnvelope
  set?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  delete?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  update?: Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutGameProfileInput | Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutGameProfileInput[]
  updateMany?: Prisma.GameSessionPlayerUpdateManyWithWhereWithoutGameProfileInput | Prisma.GameSessionPlayerUpdateManyWithWhereWithoutGameProfileInput[]
  deleteMany?: Prisma.GameSessionPlayerScalarWhereInput | Prisma.GameSessionPlayerScalarWhereInput[]
}

export type GameSessionPlayerCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.GameSessionPlayerCreateWithoutSessionInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput | Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.GameSessionPlayerCreateManySessionInputEnvelope
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
}

export type GameSessionPlayerUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.GameSessionPlayerCreateWithoutSessionInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput | Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.GameSessionPlayerCreateManySessionInputEnvelope
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
}

export type GameSessionPlayerUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.GameSessionPlayerCreateWithoutSessionInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput | Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutSessionInput | Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.GameSessionPlayerCreateManySessionInputEnvelope
  set?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  delete?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  update?: Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutSessionInput | Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.GameSessionPlayerUpdateManyWithWhereWithoutSessionInput | Prisma.GameSessionPlayerUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.GameSessionPlayerScalarWhereInput | Prisma.GameSessionPlayerScalarWhereInput[]
}

export type GameSessionPlayerUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.GameSessionPlayerCreateWithoutSessionInput[] | Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput | Prisma.GameSessionPlayerCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutSessionInput | Prisma.GameSessionPlayerUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.GameSessionPlayerCreateManySessionInputEnvelope
  set?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  delete?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  connect?: Prisma.GameSessionPlayerWhereUniqueInput | Prisma.GameSessionPlayerWhereUniqueInput[]
  update?: Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutSessionInput | Prisma.GameSessionPlayerUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.GameSessionPlayerUpdateManyWithWhereWithoutSessionInput | Prisma.GameSessionPlayerUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.GameSessionPlayerScalarWhereInput | Prisma.GameSessionPlayerScalarWhereInput[]
}

export type GameSessionPlayerCreateWithoutGameProfileInput = {
  id?: string
  isAbsent?: boolean
  leftAt?: Date | string | null
  session: Prisma.GameSessionCreateNestedOneWithoutPlayersInput
}

export type GameSessionPlayerUncheckedCreateWithoutGameProfileInput = {
  id?: string
  sessionId: string
  isAbsent?: boolean
  leftAt?: Date | string | null
}

export type GameSessionPlayerCreateOrConnectWithoutGameProfileInput = {
  where: Prisma.GameSessionPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput>
}

export type GameSessionPlayerCreateManyGameProfileInputEnvelope = {
  data: Prisma.GameSessionPlayerCreateManyGameProfileInput | Prisma.GameSessionPlayerCreateManyGameProfileInput[]
  skipDuplicates?: boolean
}

export type GameSessionPlayerUpsertWithWhereUniqueWithoutGameProfileInput = {
  where: Prisma.GameSessionPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.GameSessionPlayerUpdateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedUpdateWithoutGameProfileInput>
  create: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedCreateWithoutGameProfileInput>
}

export type GameSessionPlayerUpdateWithWhereUniqueWithoutGameProfileInput = {
  where: Prisma.GameSessionPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateWithoutGameProfileInput, Prisma.GameSessionPlayerUncheckedUpdateWithoutGameProfileInput>
}

export type GameSessionPlayerUpdateManyWithWhereWithoutGameProfileInput = {
  where: Prisma.GameSessionPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateManyMutationInput, Prisma.GameSessionPlayerUncheckedUpdateManyWithoutGameProfileInput>
}

export type GameSessionPlayerScalarWhereInput = {
  AND?: Prisma.GameSessionPlayerScalarWhereInput | Prisma.GameSessionPlayerScalarWhereInput[]
  OR?: Prisma.GameSessionPlayerScalarWhereInput[]
  NOT?: Prisma.GameSessionPlayerScalarWhereInput | Prisma.GameSessionPlayerScalarWhereInput[]
  id?: Prisma.StringFilter<"GameSessionPlayer"> | string
  sessionId?: Prisma.StringFilter<"GameSessionPlayer"> | string
  gameProfileId?: Prisma.StringFilter<"GameSessionPlayer"> | string
  isAbsent?: Prisma.BoolFilter<"GameSessionPlayer"> | boolean
  leftAt?: Prisma.DateTimeNullableFilter<"GameSessionPlayer"> | Date | string | null
}

export type GameSessionPlayerCreateWithoutSessionInput = {
  id?: string
  isAbsent?: boolean
  leftAt?: Date | string | null
  gameProfile: Prisma.GameProfileCreateNestedOneWithoutGameSessionPlayersInput
}

export type GameSessionPlayerUncheckedCreateWithoutSessionInput = {
  id?: string
  gameProfileId: string
  isAbsent?: boolean
  leftAt?: Date | string | null
}

export type GameSessionPlayerCreateOrConnectWithoutSessionInput = {
  where: Prisma.GameSessionPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput>
}

export type GameSessionPlayerCreateManySessionInputEnvelope = {
  data: Prisma.GameSessionPlayerCreateManySessionInput | Prisma.GameSessionPlayerCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type GameSessionPlayerUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.GameSessionPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.GameSessionPlayerUpdateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.GameSessionPlayerCreateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedCreateWithoutSessionInput>
}

export type GameSessionPlayerUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.GameSessionPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateWithoutSessionInput, Prisma.GameSessionPlayerUncheckedUpdateWithoutSessionInput>
}

export type GameSessionPlayerUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.GameSessionPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateManyMutationInput, Prisma.GameSessionPlayerUncheckedUpdateManyWithoutSessionInput>
}

export type GameSessionPlayerCreateManyGameProfileInput = {
  id?: string
  sessionId: string
  isAbsent?: boolean
  leftAt?: Date | string | null
}

export type GameSessionPlayerUpdateWithoutGameProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  session?: Prisma.GameSessionUpdateOneRequiredWithoutPlayersNestedInput
}

export type GameSessionPlayerUncheckedUpdateWithoutGameProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameSessionPlayerUncheckedUpdateManyWithoutGameProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameSessionPlayerCreateManySessionInput = {
  id?: string
  gameProfileId: string
  isAbsent?: boolean
  leftAt?: Date | string | null
}

export type GameSessionPlayerUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  gameProfile?: Prisma.GameProfileUpdateOneRequiredWithoutGameSessionPlayersNestedInput
}

export type GameSessionPlayerUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameSessionPlayerUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameProfileId?: Prisma.StringFieldUpdateOperationsInput | string
  isAbsent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  leftAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type GameSessionPlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  gameProfileId?: boolean
  isAbsent?: boolean
  leftAt?: boolean
  session?: boolean | Prisma.GameSessionDefaultArgs<ExtArgs>
  gameProfile?: boolean | Prisma.GameProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gameSessionPlayer"]>

export type GameSessionPlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  gameProfileId?: boolean
  isAbsent?: boolean
  leftAt?: boolean
  session?: boolean | Prisma.GameSessionDefaultArgs<ExtArgs>
  gameProfile?: boolean | Prisma.GameProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gameSessionPlayer"]>

export type GameSessionPlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  gameProfileId?: boolean
  isAbsent?: boolean
  leftAt?: boolean
  session?: boolean | Prisma.GameSessionDefaultArgs<ExtArgs>
  gameProfile?: boolean | Prisma.GameProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["gameSessionPlayer"]>

export type GameSessionPlayerSelectScalar = {
  id?: boolean
  sessionId?: boolean
  gameProfileId?: boolean
  isAbsent?: boolean
  leftAt?: boolean
}

export type GameSessionPlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "gameProfileId" | "isAbsent" | "leftAt", ExtArgs["result"]["gameSessionPlayer"]>
export type GameSessionPlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.GameSessionDefaultArgs<ExtArgs>
  gameProfile?: boolean | Prisma.GameProfileDefaultArgs<ExtArgs>
}
export type GameSessionPlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.GameSessionDefaultArgs<ExtArgs>
  gameProfile?: boolean | Prisma.GameProfileDefaultArgs<ExtArgs>
}
export type GameSessionPlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.GameSessionDefaultArgs<ExtArgs>
  gameProfile?: boolean | Prisma.GameProfileDefaultArgs<ExtArgs>
}

export type $GameSessionPlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GameSessionPlayer"
  objects: {
    session: Prisma.$GameSessionPayload<ExtArgs>
    gameProfile: Prisma.$GameProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string
    gameProfileId: string
    isAbsent: boolean
    leftAt: Date | null
  }, ExtArgs["result"]["gameSessionPlayer"]>
  composites: {}
}

export type GameSessionPlayerGetPayload<S extends boolean | null | undefined | GameSessionPlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload, S>

export type GameSessionPlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GameSessionPlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GameSessionPlayerCountAggregateInputType | true
  }

export interface GameSessionPlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GameSessionPlayer'], meta: { name: 'GameSessionPlayer' } }
  /**
   * Find zero or one GameSessionPlayer that matches the filter.
   * @param {GameSessionPlayerFindUniqueArgs} args - Arguments to find a GameSessionPlayer
   * @example
   * // Get one GameSessionPlayer
   * const gameSessionPlayer = await prisma.gameSessionPlayer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GameSessionPlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GameSessionPlayer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GameSessionPlayerFindUniqueOrThrowArgs} args - Arguments to find a GameSessionPlayer
   * @example
   * // Get one GameSessionPlayer
   * const gameSessionPlayer = await prisma.gameSessionPlayer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GameSessionPlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GameSessionPlayer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerFindFirstArgs} args - Arguments to find a GameSessionPlayer
   * @example
   * // Get one GameSessionPlayer
   * const gameSessionPlayer = await prisma.gameSessionPlayer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GameSessionPlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, GameSessionPlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GameSessionPlayer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerFindFirstOrThrowArgs} args - Arguments to find a GameSessionPlayer
   * @example
   * // Get one GameSessionPlayer
   * const gameSessionPlayer = await prisma.gameSessionPlayer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GameSessionPlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GameSessionPlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GameSessionPlayers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GameSessionPlayers
   * const gameSessionPlayers = await prisma.gameSessionPlayer.findMany()
   * 
   * // Get first 10 GameSessionPlayers
   * const gameSessionPlayers = await prisma.gameSessionPlayer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gameSessionPlayerWithIdOnly = await prisma.gameSessionPlayer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GameSessionPlayerFindManyArgs>(args?: Prisma.SelectSubset<T, GameSessionPlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GameSessionPlayer.
   * @param {GameSessionPlayerCreateArgs} args - Arguments to create a GameSessionPlayer.
   * @example
   * // Create one GameSessionPlayer
   * const GameSessionPlayer = await prisma.gameSessionPlayer.create({
   *   data: {
   *     // ... data to create a GameSessionPlayer
   *   }
   * })
   * 
   */
  create<T extends GameSessionPlayerCreateArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerCreateArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GameSessionPlayers.
   * @param {GameSessionPlayerCreateManyArgs} args - Arguments to create many GameSessionPlayers.
   * @example
   * // Create many GameSessionPlayers
   * const gameSessionPlayer = await prisma.gameSessionPlayer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GameSessionPlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, GameSessionPlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GameSessionPlayers and returns the data saved in the database.
   * @param {GameSessionPlayerCreateManyAndReturnArgs} args - Arguments to create many GameSessionPlayers.
   * @example
   * // Create many GameSessionPlayers
   * const gameSessionPlayer = await prisma.gameSessionPlayer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GameSessionPlayers and only return the `id`
   * const gameSessionPlayerWithIdOnly = await prisma.gameSessionPlayer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GameSessionPlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GameSessionPlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GameSessionPlayer.
   * @param {GameSessionPlayerDeleteArgs} args - Arguments to delete one GameSessionPlayer.
   * @example
   * // Delete one GameSessionPlayer
   * const GameSessionPlayer = await prisma.gameSessionPlayer.delete({
   *   where: {
   *     // ... filter to delete one GameSessionPlayer
   *   }
   * })
   * 
   */
  delete<T extends GameSessionPlayerDeleteArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GameSessionPlayer.
   * @param {GameSessionPlayerUpdateArgs} args - Arguments to update one GameSessionPlayer.
   * @example
   * // Update one GameSessionPlayer
   * const gameSessionPlayer = await prisma.gameSessionPlayer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GameSessionPlayerUpdateArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GameSessionPlayers.
   * @param {GameSessionPlayerDeleteManyArgs} args - Arguments to filter GameSessionPlayers to delete.
   * @example
   * // Delete a few GameSessionPlayers
   * const { count } = await prisma.gameSessionPlayer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GameSessionPlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, GameSessionPlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GameSessionPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GameSessionPlayers
   * const gameSessionPlayer = await prisma.gameSessionPlayer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GameSessionPlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GameSessionPlayers and returns the data updated in the database.
   * @param {GameSessionPlayerUpdateManyAndReturnArgs} args - Arguments to update many GameSessionPlayers.
   * @example
   * // Update many GameSessionPlayers
   * const gameSessionPlayer = await prisma.gameSessionPlayer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GameSessionPlayers and only return the `id`
   * const gameSessionPlayerWithIdOnly = await prisma.gameSessionPlayer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GameSessionPlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GameSessionPlayer.
   * @param {GameSessionPlayerUpsertArgs} args - Arguments to update or create a GameSessionPlayer.
   * @example
   * // Update or create a GameSessionPlayer
   * const gameSessionPlayer = await prisma.gameSessionPlayer.upsert({
   *   create: {
   *     // ... data to create a GameSessionPlayer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GameSessionPlayer we want to update
   *   }
   * })
   */
  upsert<T extends GameSessionPlayerUpsertArgs>(args: Prisma.SelectSubset<T, GameSessionPlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__GameSessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GameSessionPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerCountArgs} args - Arguments to filter GameSessionPlayers to count.
   * @example
   * // Count the number of GameSessionPlayers
   * const count = await prisma.gameSessionPlayer.count({
   *   where: {
   *     // ... the filter for the GameSessionPlayers we want to count
   *   }
   * })
  **/
  count<T extends GameSessionPlayerCountArgs>(
    args?: Prisma.Subset<T, GameSessionPlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GameSessionPlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GameSessionPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GameSessionPlayerAggregateArgs>(args: Prisma.Subset<T, GameSessionPlayerAggregateArgs>): Prisma.PrismaPromise<GetGameSessionPlayerAggregateType<T>>

  /**
   * Group by GameSessionPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameSessionPlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GameSessionPlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GameSessionPlayerGroupByArgs['orderBy'] }
      : { orderBy?: GameSessionPlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GameSessionPlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGameSessionPlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GameSessionPlayer model
 */
readonly fields: GameSessionPlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GameSessionPlayer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GameSessionPlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.GameSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GameSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__GameSessionClient<runtime.Types.Result.GetResult<Prisma.$GameSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  gameProfile<T extends Prisma.GameProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GameProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__GameProfileClient<runtime.Types.Result.GetResult<Prisma.$GameProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GameSessionPlayer model
 */
export interface GameSessionPlayerFieldRefs {
  readonly id: Prisma.FieldRef<"GameSessionPlayer", 'String'>
  readonly sessionId: Prisma.FieldRef<"GameSessionPlayer", 'String'>
  readonly gameProfileId: Prisma.FieldRef<"GameSessionPlayer", 'String'>
  readonly isAbsent: Prisma.FieldRef<"GameSessionPlayer", 'Boolean'>
  readonly leftAt: Prisma.FieldRef<"GameSessionPlayer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GameSessionPlayer findUnique
 */
export type GameSessionPlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which GameSessionPlayer to fetch.
   */
  where: Prisma.GameSessionPlayerWhereUniqueInput
}

/**
 * GameSessionPlayer findUniqueOrThrow
 */
export type GameSessionPlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which GameSessionPlayer to fetch.
   */
  where: Prisma.GameSessionPlayerWhereUniqueInput
}

/**
 * GameSessionPlayer findFirst
 */
export type GameSessionPlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which GameSessionPlayer to fetch.
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GameSessionPlayers to fetch.
   */
  orderBy?: Prisma.GameSessionPlayerOrderByWithRelationInput | Prisma.GameSessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GameSessionPlayers.
   */
  cursor?: Prisma.GameSessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GameSessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GameSessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GameSessionPlayers.
   */
  distinct?: Prisma.GameSessionPlayerScalarFieldEnum | Prisma.GameSessionPlayerScalarFieldEnum[]
}

/**
 * GameSessionPlayer findFirstOrThrow
 */
export type GameSessionPlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which GameSessionPlayer to fetch.
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GameSessionPlayers to fetch.
   */
  orderBy?: Prisma.GameSessionPlayerOrderByWithRelationInput | Prisma.GameSessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GameSessionPlayers.
   */
  cursor?: Prisma.GameSessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GameSessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GameSessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GameSessionPlayers.
   */
  distinct?: Prisma.GameSessionPlayerScalarFieldEnum | Prisma.GameSessionPlayerScalarFieldEnum[]
}

/**
 * GameSessionPlayer findMany
 */
export type GameSessionPlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which GameSessionPlayers to fetch.
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GameSessionPlayers to fetch.
   */
  orderBy?: Prisma.GameSessionPlayerOrderByWithRelationInput | Prisma.GameSessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GameSessionPlayers.
   */
  cursor?: Prisma.GameSessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GameSessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GameSessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GameSessionPlayers.
   */
  distinct?: Prisma.GameSessionPlayerScalarFieldEnum | Prisma.GameSessionPlayerScalarFieldEnum[]
}

/**
 * GameSessionPlayer create
 */
export type GameSessionPlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a GameSessionPlayer.
   */
  data: Prisma.XOR<Prisma.GameSessionPlayerCreateInput, Prisma.GameSessionPlayerUncheckedCreateInput>
}

/**
 * GameSessionPlayer createMany
 */
export type GameSessionPlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GameSessionPlayers.
   */
  data: Prisma.GameSessionPlayerCreateManyInput | Prisma.GameSessionPlayerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GameSessionPlayer createManyAndReturn
 */
export type GameSessionPlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * The data used to create many GameSessionPlayers.
   */
  data: Prisma.GameSessionPlayerCreateManyInput | Prisma.GameSessionPlayerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GameSessionPlayer update
 */
export type GameSessionPlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a GameSessionPlayer.
   */
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateInput, Prisma.GameSessionPlayerUncheckedUpdateInput>
  /**
   * Choose, which GameSessionPlayer to update.
   */
  where: Prisma.GameSessionPlayerWhereUniqueInput
}

/**
 * GameSessionPlayer updateMany
 */
export type GameSessionPlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GameSessionPlayers.
   */
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateManyMutationInput, Prisma.GameSessionPlayerUncheckedUpdateManyInput>
  /**
   * Filter which GameSessionPlayers to update
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * Limit how many GameSessionPlayers to update.
   */
  limit?: number
}

/**
 * GameSessionPlayer updateManyAndReturn
 */
export type GameSessionPlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * The data used to update GameSessionPlayers.
   */
  data: Prisma.XOR<Prisma.GameSessionPlayerUpdateManyMutationInput, Prisma.GameSessionPlayerUncheckedUpdateManyInput>
  /**
   * Filter which GameSessionPlayers to update
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * Limit how many GameSessionPlayers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GameSessionPlayer upsert
 */
export type GameSessionPlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the GameSessionPlayer to update in case it exists.
   */
  where: Prisma.GameSessionPlayerWhereUniqueInput
  /**
   * In case the GameSessionPlayer found by the `where` argument doesn't exist, create a new GameSessionPlayer with this data.
   */
  create: Prisma.XOR<Prisma.GameSessionPlayerCreateInput, Prisma.GameSessionPlayerUncheckedCreateInput>
  /**
   * In case the GameSessionPlayer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GameSessionPlayerUpdateInput, Prisma.GameSessionPlayerUncheckedUpdateInput>
}

/**
 * GameSessionPlayer delete
 */
export type GameSessionPlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
  /**
   * Filter which GameSessionPlayer to delete.
   */
  where: Prisma.GameSessionPlayerWhereUniqueInput
}

/**
 * GameSessionPlayer deleteMany
 */
export type GameSessionPlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GameSessionPlayers to delete
   */
  where?: Prisma.GameSessionPlayerWhereInput
  /**
   * Limit how many GameSessionPlayers to delete.
   */
  limit?: number
}

/**
 * GameSessionPlayer without action
 */
export type GameSessionPlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameSessionPlayer
   */
  select?: Prisma.GameSessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GameSessionPlayer
   */
  omit?: Prisma.GameSessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameSessionPlayerInclude<ExtArgs> | null
}
