
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserOnlineStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserOnlineStatus
 * 
 */
export type UserOnlineStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$UserOnlineStatusPayload>

export type AggregateUserOnlineStatus = {
  _count: UserOnlineStatusCountAggregateOutputType | null
  _min: UserOnlineStatusMinAggregateOutputType | null
  _max: UserOnlineStatusMaxAggregateOutputType | null
}

export type UserOnlineStatusMinAggregateOutputType = {
  userId: string | null
  isOnline: boolean | null
  lastOnline: Date | null
  updatedAt: Date | null
}

export type UserOnlineStatusMaxAggregateOutputType = {
  userId: string | null
  isOnline: boolean | null
  lastOnline: Date | null
  updatedAt: Date | null
}

export type UserOnlineStatusCountAggregateOutputType = {
  userId: number
  isOnline: number
  lastOnline: number
  onlinePlatforms: number
  updatedAt: number
  _all: number
}


export type UserOnlineStatusMinAggregateInputType = {
  userId?: true
  isOnline?: true
  lastOnline?: true
  updatedAt?: true
}

export type UserOnlineStatusMaxAggregateInputType = {
  userId?: true
  isOnline?: true
  lastOnline?: true
  updatedAt?: true
}

export type UserOnlineStatusCountAggregateInputType = {
  userId?: true
  isOnline?: true
  lastOnline?: true
  onlinePlatforms?: true
  updatedAt?: true
  _all?: true
}

export type UserOnlineStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserOnlineStatus to aggregate.
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOnlineStatuses to fetch.
   */
  orderBy?: Prisma.UserOnlineStatusOrderByWithRelationInput | Prisma.UserOnlineStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserOnlineStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOnlineStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOnlineStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserOnlineStatuses
  **/
  _count?: true | UserOnlineStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserOnlineStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserOnlineStatusMaxAggregateInputType
}

export type GetUserOnlineStatusAggregateType<T extends UserOnlineStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateUserOnlineStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserOnlineStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateUserOnlineStatus[P]>
}




export type UserOnlineStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserOnlineStatusWhereInput
  orderBy?: Prisma.UserOnlineStatusOrderByWithAggregationInput | Prisma.UserOnlineStatusOrderByWithAggregationInput[]
  by: Prisma.UserOnlineStatusScalarFieldEnum[] | Prisma.UserOnlineStatusScalarFieldEnum
  having?: Prisma.UserOnlineStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserOnlineStatusCountAggregateInputType | true
  _min?: UserOnlineStatusMinAggregateInputType
  _max?: UserOnlineStatusMaxAggregateInputType
}

export type UserOnlineStatusGroupByOutputType = {
  userId: string
  isOnline: boolean
  lastOnline: Date | null
  onlinePlatforms: runtime.JsonValue | null
  updatedAt: Date
  _count: UserOnlineStatusCountAggregateOutputType | null
  _min: UserOnlineStatusMinAggregateOutputType | null
  _max: UserOnlineStatusMaxAggregateOutputType | null
}

type GetUserOnlineStatusGroupByPayload<T extends UserOnlineStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserOnlineStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserOnlineStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserOnlineStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserOnlineStatusGroupByOutputType[P]>
      }
    >
  >



export type UserOnlineStatusWhereInput = {
  AND?: Prisma.UserOnlineStatusWhereInput | Prisma.UserOnlineStatusWhereInput[]
  OR?: Prisma.UserOnlineStatusWhereInput[]
  NOT?: Prisma.UserOnlineStatusWhereInput | Prisma.UserOnlineStatusWhereInput[]
  userId?: Prisma.StringFilter<"UserOnlineStatus"> | string
  isOnline?: Prisma.BoolFilter<"UserOnlineStatus"> | boolean
  lastOnline?: Prisma.DateTimeNullableFilter<"UserOnlineStatus"> | Date | string | null
  onlinePlatforms?: Prisma.JsonNullableFilter<"UserOnlineStatus">
  updatedAt?: Prisma.DateTimeFilter<"UserOnlineStatus"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserOnlineStatusOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  lastOnline?: Prisma.SortOrderInput | Prisma.SortOrder
  onlinePlatforms?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserOnlineStatusWhereUniqueInput = Prisma.AtLeast<{
  userId?: string
  AND?: Prisma.UserOnlineStatusWhereInput | Prisma.UserOnlineStatusWhereInput[]
  OR?: Prisma.UserOnlineStatusWhereInput[]
  NOT?: Prisma.UserOnlineStatusWhereInput | Prisma.UserOnlineStatusWhereInput[]
  isOnline?: Prisma.BoolFilter<"UserOnlineStatus"> | boolean
  lastOnline?: Prisma.DateTimeNullableFilter<"UserOnlineStatus"> | Date | string | null
  onlinePlatforms?: Prisma.JsonNullableFilter<"UserOnlineStatus">
  updatedAt?: Prisma.DateTimeFilter<"UserOnlineStatus"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "userId" | "userId">

export type UserOnlineStatusOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  lastOnline?: Prisma.SortOrderInput | Prisma.SortOrder
  onlinePlatforms?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserOnlineStatusCountOrderByAggregateInput
  _max?: Prisma.UserOnlineStatusMaxOrderByAggregateInput
  _min?: Prisma.UserOnlineStatusMinOrderByAggregateInput
}

export type UserOnlineStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserOnlineStatusScalarWhereWithAggregatesInput | Prisma.UserOnlineStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserOnlineStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserOnlineStatusScalarWhereWithAggregatesInput | Prisma.UserOnlineStatusScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserOnlineStatus"> | string
  isOnline?: Prisma.BoolWithAggregatesFilter<"UserOnlineStatus"> | boolean
  lastOnline?: Prisma.DateTimeNullableWithAggregatesFilter<"UserOnlineStatus"> | Date | string | null
  onlinePlatforms?: Prisma.JsonNullableWithAggregatesFilter<"UserOnlineStatus">
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserOnlineStatus"> | Date | string
}

export type UserOnlineStatusCreateInput = {
  isOnline?: boolean
  lastOnline?: Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutOnlineStatusInput
}

export type UserOnlineStatusUncheckedCreateInput = {
  userId: string
  isOnline?: boolean
  lastOnline?: Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type UserOnlineStatusUpdateInput = {
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastOnline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutOnlineStatusNestedInput
}

export type UserOnlineStatusUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastOnline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOnlineStatusCreateManyInput = {
  userId: string
  isOnline?: boolean
  lastOnline?: Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type UserOnlineStatusUpdateManyMutationInput = {
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastOnline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOnlineStatusUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastOnline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOnlineStatusNullableScalarRelationFilter = {
  is?: Prisma.UserOnlineStatusWhereInput | null
  isNot?: Prisma.UserOnlineStatusWhereInput | null
}

export type UserOnlineStatusCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  lastOnline?: Prisma.SortOrder
  onlinePlatforms?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserOnlineStatusMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  lastOnline?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserOnlineStatusMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  lastOnline?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserOnlineStatusCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserOnlineStatusCreateWithoutUserInput, Prisma.UserOnlineStatusUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserOnlineStatusCreateOrConnectWithoutUserInput
  connect?: Prisma.UserOnlineStatusWhereUniqueInput
}

export type UserOnlineStatusUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserOnlineStatusCreateWithoutUserInput, Prisma.UserOnlineStatusUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserOnlineStatusCreateOrConnectWithoutUserInput
  connect?: Prisma.UserOnlineStatusWhereUniqueInput
}

export type UserOnlineStatusUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserOnlineStatusCreateWithoutUserInput, Prisma.UserOnlineStatusUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserOnlineStatusCreateOrConnectWithoutUserInput
  upsert?: Prisma.UserOnlineStatusUpsertWithoutUserInput
  disconnect?: Prisma.UserOnlineStatusWhereInput | boolean
  delete?: Prisma.UserOnlineStatusWhereInput | boolean
  connect?: Prisma.UserOnlineStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserOnlineStatusUpdateToOneWithWhereWithoutUserInput, Prisma.UserOnlineStatusUpdateWithoutUserInput>, Prisma.UserOnlineStatusUncheckedUpdateWithoutUserInput>
}

export type UserOnlineStatusUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserOnlineStatusCreateWithoutUserInput, Prisma.UserOnlineStatusUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.UserOnlineStatusCreateOrConnectWithoutUserInput
  upsert?: Prisma.UserOnlineStatusUpsertWithoutUserInput
  disconnect?: Prisma.UserOnlineStatusWhereInput | boolean
  delete?: Prisma.UserOnlineStatusWhereInput | boolean
  connect?: Prisma.UserOnlineStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserOnlineStatusUpdateToOneWithWhereWithoutUserInput, Prisma.UserOnlineStatusUpdateWithoutUserInput>, Prisma.UserOnlineStatusUncheckedUpdateWithoutUserInput>
}

export type UserOnlineStatusCreateWithoutUserInput = {
  isOnline?: boolean
  lastOnline?: Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type UserOnlineStatusUncheckedCreateWithoutUserInput = {
  isOnline?: boolean
  lastOnline?: Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Date | string
}

export type UserOnlineStatusCreateOrConnectWithoutUserInput = {
  where: Prisma.UserOnlineStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.UserOnlineStatusCreateWithoutUserInput, Prisma.UserOnlineStatusUncheckedCreateWithoutUserInput>
}

export type UserOnlineStatusUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.UserOnlineStatusUpdateWithoutUserInput, Prisma.UserOnlineStatusUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserOnlineStatusCreateWithoutUserInput, Prisma.UserOnlineStatusUncheckedCreateWithoutUserInput>
  where?: Prisma.UserOnlineStatusWhereInput
}

export type UserOnlineStatusUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.UserOnlineStatusWhereInput
  data: Prisma.XOR<Prisma.UserOnlineStatusUpdateWithoutUserInput, Prisma.UserOnlineStatusUncheckedUpdateWithoutUserInput>
}

export type UserOnlineStatusUpdateWithoutUserInput = {
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastOnline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOnlineStatusUncheckedUpdateWithoutUserInput = {
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastOnline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  onlinePlatforms?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserOnlineStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  isOnline?: boolean
  lastOnline?: boolean
  onlinePlatforms?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userOnlineStatus"]>

export type UserOnlineStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  isOnline?: boolean
  lastOnline?: boolean
  onlinePlatforms?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userOnlineStatus"]>

export type UserOnlineStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  isOnline?: boolean
  lastOnline?: boolean
  onlinePlatforms?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userOnlineStatus"]>

export type UserOnlineStatusSelectScalar = {
  userId?: boolean
  isOnline?: boolean
  lastOnline?: boolean
  onlinePlatforms?: boolean
  updatedAt?: boolean
}

export type UserOnlineStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "isOnline" | "lastOnline" | "onlinePlatforms" | "updatedAt", ExtArgs["result"]["userOnlineStatus"]>
export type UserOnlineStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserOnlineStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserOnlineStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserOnlineStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserOnlineStatus"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    isOnline: boolean
    lastOnline: Date | null
    onlinePlatforms: runtime.JsonValue | null
    updatedAt: Date
  }, ExtArgs["result"]["userOnlineStatus"]>
  composites: {}
}

export type UserOnlineStatusGetPayload<S extends boolean | null | undefined | UserOnlineStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload, S>

export type UserOnlineStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserOnlineStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserOnlineStatusCountAggregateInputType | true
  }

export interface UserOnlineStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserOnlineStatus'], meta: { name: 'UserOnlineStatus' } }
  /**
   * Find zero or one UserOnlineStatus that matches the filter.
   * @param {UserOnlineStatusFindUniqueArgs} args - Arguments to find a UserOnlineStatus
   * @example
   * // Get one UserOnlineStatus
   * const userOnlineStatus = await prisma.userOnlineStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserOnlineStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserOnlineStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserOnlineStatusFindUniqueOrThrowArgs} args - Arguments to find a UserOnlineStatus
   * @example
   * // Get one UserOnlineStatus
   * const userOnlineStatus = await prisma.userOnlineStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserOnlineStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserOnlineStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusFindFirstArgs} args - Arguments to find a UserOnlineStatus
   * @example
   * // Get one UserOnlineStatus
   * const userOnlineStatus = await prisma.userOnlineStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserOnlineStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, UserOnlineStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserOnlineStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusFindFirstOrThrowArgs} args - Arguments to find a UserOnlineStatus
   * @example
   * // Get one UserOnlineStatus
   * const userOnlineStatus = await prisma.userOnlineStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserOnlineStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserOnlineStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserOnlineStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserOnlineStatuses
   * const userOnlineStatuses = await prisma.userOnlineStatus.findMany()
   * 
   * // Get first 10 UserOnlineStatuses
   * const userOnlineStatuses = await prisma.userOnlineStatus.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userOnlineStatusWithUserIdOnly = await prisma.userOnlineStatus.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserOnlineStatusFindManyArgs>(args?: Prisma.SelectSubset<T, UserOnlineStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserOnlineStatus.
   * @param {UserOnlineStatusCreateArgs} args - Arguments to create a UserOnlineStatus.
   * @example
   * // Create one UserOnlineStatus
   * const UserOnlineStatus = await prisma.userOnlineStatus.create({
   *   data: {
   *     // ... data to create a UserOnlineStatus
   *   }
   * })
   * 
   */
  create<T extends UserOnlineStatusCreateArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusCreateArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserOnlineStatuses.
   * @param {UserOnlineStatusCreateManyArgs} args - Arguments to create many UserOnlineStatuses.
   * @example
   * // Create many UserOnlineStatuses
   * const userOnlineStatus = await prisma.userOnlineStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserOnlineStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, UserOnlineStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserOnlineStatuses and returns the data saved in the database.
   * @param {UserOnlineStatusCreateManyAndReturnArgs} args - Arguments to create many UserOnlineStatuses.
   * @example
   * // Create many UserOnlineStatuses
   * const userOnlineStatus = await prisma.userOnlineStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserOnlineStatuses and only return the `userId`
   * const userOnlineStatusWithUserIdOnly = await prisma.userOnlineStatus.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserOnlineStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserOnlineStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserOnlineStatus.
   * @param {UserOnlineStatusDeleteArgs} args - Arguments to delete one UserOnlineStatus.
   * @example
   * // Delete one UserOnlineStatus
   * const UserOnlineStatus = await prisma.userOnlineStatus.delete({
   *   where: {
   *     // ... filter to delete one UserOnlineStatus
   *   }
   * })
   * 
   */
  delete<T extends UserOnlineStatusDeleteArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserOnlineStatus.
   * @param {UserOnlineStatusUpdateArgs} args - Arguments to update one UserOnlineStatus.
   * @example
   * // Update one UserOnlineStatus
   * const userOnlineStatus = await prisma.userOnlineStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserOnlineStatusUpdateArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserOnlineStatuses.
   * @param {UserOnlineStatusDeleteManyArgs} args - Arguments to filter UserOnlineStatuses to delete.
   * @example
   * // Delete a few UserOnlineStatuses
   * const { count } = await prisma.userOnlineStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserOnlineStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserOnlineStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserOnlineStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserOnlineStatuses
   * const userOnlineStatus = await prisma.userOnlineStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserOnlineStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserOnlineStatuses and returns the data updated in the database.
   * @param {UserOnlineStatusUpdateManyAndReturnArgs} args - Arguments to update many UserOnlineStatuses.
   * @example
   * // Update many UserOnlineStatuses
   * const userOnlineStatus = await prisma.userOnlineStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserOnlineStatuses and only return the `userId`
   * const userOnlineStatusWithUserIdOnly = await prisma.userOnlineStatus.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserOnlineStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserOnlineStatus.
   * @param {UserOnlineStatusUpsertArgs} args - Arguments to update or create a UserOnlineStatus.
   * @example
   * // Update or create a UserOnlineStatus
   * const userOnlineStatus = await prisma.userOnlineStatus.upsert({
   *   create: {
   *     // ... data to create a UserOnlineStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserOnlineStatus we want to update
   *   }
   * })
   */
  upsert<T extends UserOnlineStatusUpsertArgs>(args: Prisma.SelectSubset<T, UserOnlineStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__UserOnlineStatusClient<runtime.Types.Result.GetResult<Prisma.$UserOnlineStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserOnlineStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusCountArgs} args - Arguments to filter UserOnlineStatuses to count.
   * @example
   * // Count the number of UserOnlineStatuses
   * const count = await prisma.userOnlineStatus.count({
   *   where: {
   *     // ... the filter for the UserOnlineStatuses we want to count
   *   }
   * })
  **/
  count<T extends UserOnlineStatusCountArgs>(
    args?: Prisma.Subset<T, UserOnlineStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserOnlineStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserOnlineStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserOnlineStatusAggregateArgs>(args: Prisma.Subset<T, UserOnlineStatusAggregateArgs>): Prisma.PrismaPromise<GetUserOnlineStatusAggregateType<T>>

  /**
   * Group by UserOnlineStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOnlineStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserOnlineStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserOnlineStatusGroupByArgs['orderBy'] }
      : { orderBy?: UserOnlineStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserOnlineStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserOnlineStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserOnlineStatus model
 */
readonly fields: UserOnlineStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserOnlineStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserOnlineStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserOnlineStatus model
 */
export interface UserOnlineStatusFieldRefs {
  readonly userId: Prisma.FieldRef<"UserOnlineStatus", 'String'>
  readonly isOnline: Prisma.FieldRef<"UserOnlineStatus", 'Boolean'>
  readonly lastOnline: Prisma.FieldRef<"UserOnlineStatus", 'DateTime'>
  readonly onlinePlatforms: Prisma.FieldRef<"UserOnlineStatus", 'Json'>
  readonly updatedAt: Prisma.FieldRef<"UserOnlineStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserOnlineStatus findUnique
 */
export type UserOnlineStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * Filter, which UserOnlineStatus to fetch.
   */
  where: Prisma.UserOnlineStatusWhereUniqueInput
}

/**
 * UserOnlineStatus findUniqueOrThrow
 */
export type UserOnlineStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * Filter, which UserOnlineStatus to fetch.
   */
  where: Prisma.UserOnlineStatusWhereUniqueInput
}

/**
 * UserOnlineStatus findFirst
 */
export type UserOnlineStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * Filter, which UserOnlineStatus to fetch.
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOnlineStatuses to fetch.
   */
  orderBy?: Prisma.UserOnlineStatusOrderByWithRelationInput | Prisma.UserOnlineStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserOnlineStatuses.
   */
  cursor?: Prisma.UserOnlineStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOnlineStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOnlineStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserOnlineStatuses.
   */
  distinct?: Prisma.UserOnlineStatusScalarFieldEnum | Prisma.UserOnlineStatusScalarFieldEnum[]
}

/**
 * UserOnlineStatus findFirstOrThrow
 */
export type UserOnlineStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * Filter, which UserOnlineStatus to fetch.
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOnlineStatuses to fetch.
   */
  orderBy?: Prisma.UserOnlineStatusOrderByWithRelationInput | Prisma.UserOnlineStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserOnlineStatuses.
   */
  cursor?: Prisma.UserOnlineStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOnlineStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOnlineStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserOnlineStatuses.
   */
  distinct?: Prisma.UserOnlineStatusScalarFieldEnum | Prisma.UserOnlineStatusScalarFieldEnum[]
}

/**
 * UserOnlineStatus findMany
 */
export type UserOnlineStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * Filter, which UserOnlineStatuses to fetch.
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserOnlineStatuses to fetch.
   */
  orderBy?: Prisma.UserOnlineStatusOrderByWithRelationInput | Prisma.UserOnlineStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserOnlineStatuses.
   */
  cursor?: Prisma.UserOnlineStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserOnlineStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserOnlineStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserOnlineStatuses.
   */
  distinct?: Prisma.UserOnlineStatusScalarFieldEnum | Prisma.UserOnlineStatusScalarFieldEnum[]
}

/**
 * UserOnlineStatus create
 */
export type UserOnlineStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a UserOnlineStatus.
   */
  data: Prisma.XOR<Prisma.UserOnlineStatusCreateInput, Prisma.UserOnlineStatusUncheckedCreateInput>
}

/**
 * UserOnlineStatus createMany
 */
export type UserOnlineStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserOnlineStatuses.
   */
  data: Prisma.UserOnlineStatusCreateManyInput | Prisma.UserOnlineStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserOnlineStatus createManyAndReturn
 */
export type UserOnlineStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * The data used to create many UserOnlineStatuses.
   */
  data: Prisma.UserOnlineStatusCreateManyInput | Prisma.UserOnlineStatusCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserOnlineStatus update
 */
export type UserOnlineStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a UserOnlineStatus.
   */
  data: Prisma.XOR<Prisma.UserOnlineStatusUpdateInput, Prisma.UserOnlineStatusUncheckedUpdateInput>
  /**
   * Choose, which UserOnlineStatus to update.
   */
  where: Prisma.UserOnlineStatusWhereUniqueInput
}

/**
 * UserOnlineStatus updateMany
 */
export type UserOnlineStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserOnlineStatuses.
   */
  data: Prisma.XOR<Prisma.UserOnlineStatusUpdateManyMutationInput, Prisma.UserOnlineStatusUncheckedUpdateManyInput>
  /**
   * Filter which UserOnlineStatuses to update
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * Limit how many UserOnlineStatuses to update.
   */
  limit?: number
}

/**
 * UserOnlineStatus updateManyAndReturn
 */
export type UserOnlineStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * The data used to update UserOnlineStatuses.
   */
  data: Prisma.XOR<Prisma.UserOnlineStatusUpdateManyMutationInput, Prisma.UserOnlineStatusUncheckedUpdateManyInput>
  /**
   * Filter which UserOnlineStatuses to update
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * Limit how many UserOnlineStatuses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserOnlineStatus upsert
 */
export type UserOnlineStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the UserOnlineStatus to update in case it exists.
   */
  where: Prisma.UserOnlineStatusWhereUniqueInput
  /**
   * In case the UserOnlineStatus found by the `where` argument doesn't exist, create a new UserOnlineStatus with this data.
   */
  create: Prisma.XOR<Prisma.UserOnlineStatusCreateInput, Prisma.UserOnlineStatusUncheckedCreateInput>
  /**
   * In case the UserOnlineStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserOnlineStatusUpdateInput, Prisma.UserOnlineStatusUncheckedUpdateInput>
}

/**
 * UserOnlineStatus delete
 */
export type UserOnlineStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
  /**
   * Filter which UserOnlineStatus to delete.
   */
  where: Prisma.UserOnlineStatusWhereUniqueInput
}

/**
 * UserOnlineStatus deleteMany
 */
export type UserOnlineStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserOnlineStatuses to delete
   */
  where?: Prisma.UserOnlineStatusWhereInput
  /**
   * Limit how many UserOnlineStatuses to delete.
   */
  limit?: number
}

/**
 * UserOnlineStatus without action
 */
export type UserOnlineStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserOnlineStatus
   */
  select?: Prisma.UserOnlineStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOnlineStatus
   */
  omit?: Prisma.UserOnlineStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOnlineStatusInclude<ExtArgs> | null
}
