export enum AuditActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REVOKE_SESSION = 'REVOKE_SESSION',
  BAN_USER = 'BAN_USER',
  UNBAN_USER = 'UNBAN_USER',
  PROCESS_REPORT = 'PROCESS_REPORT',
}
